-- 015 — SEED: the products we sell today, and the legacy strings that route to them.
--
-- Idempotent, keyed on products.code. Re-running never duplicates and never
-- overwrites an edit Chris has made from the admin screen — the WHERE NOT EXISTS
-- guard means this file inserts once and is inert thereafter. If a price or a
-- name needs changing, change it in the UI; do not edit this file.
--
-- Source: Master Rebuild Spec §12. Names are the spec's names.
-- Prices here are DEFAULTS ONLY — a prefill on the sale form. The number that
-- matters is sales.agreed_price, set per client.

INSERT INTO products (
  org_id, code, name, description, category,
  default_price, min_price, max_price, price_is_variable,
  default_success_fee_percent, sort_order, notes
)
SELECT o.id, v.code, v.name, v.description, v.category,
       v.default_price, v.min_price, v.max_price, v.price_is_variable,
       v.success_fee, v.sort_order, v.notes
  FROM orgs o
  CROSS JOIN (VALUES
    (
      'diagnostic', '$32 Diagnostic',
      'Entry diagnostic. Triggers analysis.completed and the 6-tier decision.',
      'diagnostic',
      32.00, NULL::numeric(14,2), NULL::numeric(14,2), false,
      NULL::numeric, 10,
      'Effectively fixed price. price_is_variable=false so the sale form locks it.'
    ),
    (
      'card-stacking-dfy', 'Card Stacking DFY',
      'Done-for-you card stacking. Deposit up front, success fee on funding.',
      'funding',
      3000.00, NULL, NULL, true,
      10.0000, 20,
      'Deposit is the front end. 10% success fee is the back end, invoiced on round.funded (spec §12, ports AX20/AX21).'
    ),
    (
      'consulting-package', 'Consulting Services Package',
      'DIY consulting. Variable per client via the Commas custom-amount checkout.',
      'consulting',
      1000.00, NULL, NULL, true,
      NULL::numeric, 30,
      'Name must stay EXACTLY this — it is the product Chris creates in Commas (spec §15.2). Renaming it here keeps the old name as a routing alias, but coordinate with Commas before renaming.'
    ),
    (
      'repair-bundle', 'Credit Repair Bundle',
      'Credit repair bundle.',
      'repair',
      2000.00, NULL, NULL, true,
      NULL::numeric, 40,
      NULL
    ),
    (
      'inquiry-removal', 'Inquiry Removal',
      'Inquiry removal. Price set per engagement.',
      'inquiry_removal',
      NULL::numeric, NULL, NULL, true,
      NULL::numeric, 50,
      'No default price on record. Sale form requires the closer to enter one.'
    )
  ) AS v(code, name, description, category,
         default_price, min_price, max_price, price_is_variable,
         success_fee, sort_order, notes)
 WHERE o.is_default
   AND NOT EXISTS (
     SELECT 1 FROM products p WHERE p.org_id = o.id AND lower(p.code) = lower(v.code)
   );

-- ---------------------------------------------------------------------------
-- Legacy + provider routing strings.
--
-- These are the product strings that already exist in the wild: the spec's own
-- labels, GHL's labels, and what Commas/ClickFunnels webhooks send. They land in
-- transactions.product_name (001_init.sql) as text, and resolve to a product
-- record through here.
--
-- Note the amounts embedded in some of these strings ('$3,000 deposit'). They
-- are matched as NAMES — opaque labels — never parsed as money. Hard Rule 4
-- holds: routing never looks at a dollar amount.
-- ---------------------------------------------------------------------------
INSERT INTO product_aliases (org_id, product_id, alias, source)
SELECT p.org_id, p.id, v.alias, v.source
  FROM products p
  JOIN orgs o ON o.id = p.org_id AND o.is_default
  JOIN (VALUES
    ('diagnostic',         '$32 diagnostic',              'legacy'),
    ('diagnostic',         '32 diagnostic',               'legacy'),
    ('diagnostic',         'Diagnostic',                  'legacy'),
    ('card-stacking-dfy',  '$3,000 deposit',              'legacy'),
    ('card-stacking-dfy',  '$3000 deposit',               'legacy'),
    ('card-stacking-dfy',  'Card Stacking',               'legacy'),
    ('consulting-package', 'Consulting Services Package', 'commas'),
    ('repair-bundle',      '$2,000 credit repair bundle', 'legacy'),
    ('repair-bundle',      '$2000 credit repair bundle',  'legacy'),
    ('repair-bundle',      'Credit Repair',               'legacy'),
    ('inquiry-removal',    'Inquiry Removal Service',     'legacy')
  ) AS v(code, alias, source) ON lower(v.code) = lower(p.code)
 WHERE NOT EXISTS (
   SELECT 1 FROM product_aliases a
    WHERE a.org_id = p.org_id AND lower(a.alias) = lower(v.alias)
 );
