-- 057_conversations_unique_channel.sql — make `conversations` writable by giving
-- it the constraint its own definition already implies.
--
-- WHY THIS EXISTS. `conversations` has been in 001_init.sql since the first
-- migration and NOTHING HAS EVER WRITTEN A ROW TO IT. Grep the tree: no INSERT,
-- no UPDATE, no SELECT anywhere in src/ or api/. Its comment says "threaded per
-- client per channel", and `messages.conversation_id` plus `idx_messages_convo`
-- plus the `fk_messages_convo` foreign key were all built to hang off it — but
-- src/handlers/comms.mjs inserts every SMS and every voice-call messages row
-- with conversation_id left NULL. The thread column exists, the thread table
-- exists, and the link between them has never been made. This migration is the
-- schema half of making it.
--
-- ONE ROW PER (client_id, channel) IS THE WHOLE POINT. The writer in
-- src/conversations/store.mjs is an UPSERT: every inbound SMS lands on the same
-- sms thread for that client rather than minting a new row per message. An
-- upsert needs a unique index to name as its conflict target, and the existing
-- `idx_convo_client ON conversations(client_id, channel)` IS NOT UNIQUE — an
-- ON CONFLICT against it is a syntax error, not a slow path. Without this index
-- the writer cannot exist at all; with it, ten thousand inbound messages
-- maintain exactly one sms conversation per client.
--
-- COULD DUPLICATES ALREADY EXIST? No, and the reason is checkable rather than
-- hopeful: the table has no writer. In every environment created by this repo
-- `conversations` is empty, so the index builds against zero rows. If some
-- hand-loaded database DOES hold two rows for one (client, channel), this
-- migration FAILS LOUDLY and a human looks at it. That is deliberate. The
-- alternative — a de-duplicating DELETE ahead of the index — would silently
-- destroy one of two summaries a human may have written, and would NULL out the
-- conversation_id of every message pointing at the loser (fk_messages_convo is
-- ON DELETE SET NULL). Losing a thread quietly is strictly worse than a failed
-- migration.
--
-- SENTIMENT IS NOT TOUCHED HERE, AND WILL NOT BE WRITTEN. The column carries the
-- comment "Hot | Warm | Cold" and nothing in this codebase computes that value:
-- there is no classifier, no scoring pass, no source field on any inbound
-- payload that carries it. src/config/lead-temperature.mjs derives a hot/warm
-- reading from WHICH EVENTS FIRED, not from what was said in a conversation, and
-- it is a different question with a different answer — a client who booked a
-- call is "hot" there while the sms thread they never replied to is not. So
-- `sentiment` stays NULL and the writer never names the column. A guessed
-- sentiment is read aloud on a sales call; a blank one prompts someone to look.
-- No CHECK constraint is added to it either, because constraining a vocabulary
-- nobody has agreed to would be inventing the decision rather than recording it.
--
-- NO CHECK ON `channel` EITHER, FOR THE SAME REASON. `messages.channel` is
-- documented as sms | email | voice and is free text; the writer copies whatever
-- value the messages row already carries instead of minting a parallel
-- vocabulary. Pinning a CHECK here would either duplicate that undeclared
-- vocabulary or reject a channel the messages table happily accepts, and the two
-- columns must agree.
--
-- `idx_convo_client` IS LEFT IN PLACE even though the unique index below now
-- covers exactly the same columns in the same order and makes it redundant.
-- Dropping an index that db/schema/001_init.sql created is a decision about the
-- frozen baseline, not about this feature, and it buys one saved write per
-- inbound message. It is flagged here so whoever does a storage pass can take it
-- knowingly: `DROP INDEX IF EXISTS idx_convo_client;` is safe once this lands.
--
-- WHAT IS DELIBERATELY NOT ADDED: a second index for the reader's
-- `ORDER BY last_pulse_at DESC NULLS LAST`. listConversations() filters by
-- client_id and sorts within that client, and this very migration caps a client
-- at one row per channel — so the sort runs over a handful of rows reached
-- through the unique index below. An extra index would add a write on every
-- inbound message to speed up a sort of three rows. If a cross-client sweep ever
-- appears ("threads with no pulse in 14 days"), that reader can bring its own
-- index and justify it against a real query plan.

-- The upsert's conflict target: one conversation per client per channel.
CREATE UNIQUE INDEX IF NOT EXISTS uq_conversations_client_channel
  ON conversations (client_id, channel);
