-- 060_shifts_one_open.sql — make "one open shift per staff member" true.
--
-- WHY THIS EXISTS. The build plan for the clock-in service states that the
-- shape is already enforced, citing `idx_shifts_open`. It is not. The actual
-- definition, db/schema/001_init.sql line 402, is:
--
--     CREATE INDEX idx_shifts_open ON shifts(staff_id) WHERE ended_at IS NULL;
--
-- A plain partial index. It makes "find this person's open shift" fast and
-- promises nothing about how many there are. Nothing in the database — and,
-- until src/shifts/store.mjs, nothing in the application either — prevented a
-- staff member from holding two, five, or fifty simultaneously open shifts.
-- The word `open` in the index name is what did the arguing; the DDL never did.
--
-- WHY IT MATTERS MORE THAN A DUPLICATE ROW USUALLY DOES. Shifts are the hours
-- record. Every downstream reader of this table — hours worked, presence,
-- "who was on the file at 14:00", and whatever payroll eventually hangs off it
-- — computes over (started_at, ended_at) pairs. Two overlapping open rows do
-- not produce a visible error anywhere; they produce a person who was on shift
-- twice at once, and therefore double the hours, silently, in a number that
-- someone is eventually paid against. There is no read that flags it. The only
-- place it can be stopped is here.
--
-- HOW IT HAPPENS WITHOUT ANYONE DOING ANYTHING WRONG. A double-submitted
-- clock-in button. A retried request after a timeout where the first attempt
-- actually committed. Two browser tabs. A phone and a desktop. None of these
-- are misuse; all of them are two INSERTs racing, and a check-then-insert in
-- application code cannot close the window between the SELECT and the INSERT.
-- Only a unique index can, because it is evaluated at write time by the one
-- component that sees both transactions.
--
-- THE CONSTRAINT. Same key and same predicate as the existing index, with the
-- uniqueness that was assumed all along. `staff_id` alone, not
-- (org_id, staff_id): staff.id is a global primary key and a staff row belongs
-- to exactly one org, so adding org_id would widen the key to permit one open
-- shift per org per person — which is the bug, restated.
CREATE UNIQUE INDEX IF NOT EXISTS uq_shifts_one_open
  ON shifts (staff_id)
  WHERE ended_at IS NULL;

-- WILL THIS FAIL ON A DATABASE THAT ALREADY HAS DUPLICATES? YES, AND
-- DELIBERATELY SO. CREATE UNIQUE INDEX validates the existing rows. If any
-- staff_id already has more than one row with ended_at IS NULL, this statement
-- aborts with:
--
--     ERROR: could not create unique index "uq_shifts_one_open"
--     DETAIL: Key (staff_id)=(...) is duplicated.
--
-- db/migrate.mjs runs each file in its own transaction and rethrows on failure,
-- so the whole run stops, this file is NOT recorded in schema_migrations, and
-- re-running after the data is fixed applies it normally. A failed run here
-- costs a retry, not a half-applied schema.
--
-- On the database this was written against the pre-condition holds — `shifts`
-- has never had a writer, so it is empty. The failure mode is stated because
-- some other environment may have been hand-seeded. Find the offenders with:
--
--     SELECT staff_id, count(*), array_agg(id ORDER BY started_at)
--       FROM shifts WHERE ended_at IS NULL
--      GROUP BY staff_id HAVING count(*) > 1;
--
-- WHAT WAS DELIBERATELY NOT DONE (1): NO AUTOMATIC REPAIR. This migration does
-- not close duplicate open shifts for you. Closing one means choosing which of
-- the two is real and choosing an ended_at for the other, and there is no
-- source in this codebase for either decision. Setting ended_at = now() would
-- be the obvious one-liner and it would write hours that nobody worked onto a
-- timesheet — inventing a value where the honest answer is "an operator has to
-- look". src/shifts/store.mjs has the same hole at
-- STALE_SHIFT_HOURS_PLACEHOLDER and reports it rather than filling it. If a
-- repair is wanted it belongs in its own migration, after somebody decides the
-- rule, not smuggled into the constraint that exposed the problem.
--
-- WHAT WAS DELIBERATELY NOT DONE (2): idx_shifts_open IS NOT DROPPED. The new
-- index has the same key and the same predicate, so it makes the old one
-- redundant for lookups and the tidy move would be to drop it. It is kept
-- because 001_init.sql is frozen and creates it by name: an environment
-- restored from schema alone must not end up with the plain index missing and
-- the unique one not yet applied, and the cost of keeping it is one small
-- partial index over a table with at most one row per staff member. The
-- redundancy is deliberate and documented, not an oversight.
--
-- WHAT WAS DELIBERATELY NOT DONE (3): NO CHECK ON ended_at >= started_at, and
-- no exclusion constraint against overlapping CLOSED shifts. Both are real
-- invariants and neither is this migration's job. The overlap question in
-- particular needs btree_gist and a decision about whether an adjacent shift
-- may share a boundary instant; that is a schema decision with an operator in
-- the room, and pretending to settle it here would be the same mistake the
-- plan made about idx_shifts_open — a constraint that looks like it enforces
-- something it does not.
