-- 067_mail_response_idempotency.sql — the one thing `mail_responses` cannot
-- enforce today: that a response nobody can identify is only counted once.
--
-- *** NOTHING IN THIS FILE MAILS ANYTHING, AND NOTHING IN THIS FILE CAN BE
-- *** SWITCHED ON TO MAKE IT MAIL ANYTHING.
-- Same gate as 065_mail_campaigns.sql and src/mail/README.md: prescreen data
-- requires a firm offer of credit under the FCRA, and no drop happens until the
-- FCRA research, Deluxe compliance review and legal sign-off on lender-of-record
-- are all in. This file adds ONE INDEX. There is no scheduler, no send path, no
-- activation flag, and nothing here that a later env var could flip.
--
--
-- WHAT WAS BROKEN. 065 gave `mail_responses` exactly one uniqueness rule:
--
--   CREATE UNIQUE INDEX uq_mail_responses_provider_ref
--     ON mail_responses (provider_ref) WHERE provider_ref IS NOT NULL;
--
-- That is the right rule and it is doing real work — re-importing a call log
-- cannot double-count a call, because Twilio's CallSid adjudicates it. But it is
-- PARTIAL, and the predicate is exactly backwards from the case this repo hits
-- first. The response path that actually exists today is the PURL/QR one:
-- a slug printed on a mail piece, scanned off a public URL. That arrives with no
-- provider identifier of any kind — there is no CallSid, no MessageSid, nothing.
-- So every single web response falls in the `provider_ref IS NULL` gap where the
-- unique index does not apply, and the database will happily accept the same
-- scan five times.
--
-- The consequence is not a duplicate row, it is a WRONG NUMBER. `mail_responses`
-- is what attributionByCampaign() counts (src/mail/responses.mjs). One person
-- who scans a QR code, loses signal, and scans it again would read out as two
-- respondents against a campaign whose whole purpose is measuring response rate.
-- A response rate that silently double-counts is worse than no response rate,
-- because it looks like an answer.
--
--
-- WHY A DATABASE CONSTRAINT AND NOT JUST A GUARD SELECT. src/mail/responses.mjs
-- does hold a guard, and the guard is where the readable "you already responded"
-- answer comes from. But a guard SELECT followed by an INSERT is two statements,
-- and a printed QR code is precisely the input that arrives twice at once: the
-- browser retries, the scanner app prefetches the URL and then opens it, the
-- person taps twice because nothing appeared to happen. Two concurrent requests
-- both read "no prior response" and both insert. Only a unique index can settle
-- a race between two writers. This is the same reasoning 065 wrote out for
-- uq_mail_tracked_numbers_active, and the same reasoning
-- 060_shifts_one_open.sql wrote out for uq_shifts_one_open.
--
--
-- THE RULE THIS ENCODES, STATED PLAINLY: *** YOU CAN ONLY DEDUPE WHAT YOU CAN
-- IDENTIFY. *** Two responses on the same record and the same channel that both
-- arrive with NO identifier are indistinguishable — not "probably the same", but
-- literally the same as far as anything recorded about them goes. Treating them
-- as one response is therefore a description of what is known, not a guess. Two
-- responses that DO carry identifiers are distinguishable, and both are kept.
--
-- Hence the predicate `WHERE provider_ref IS NULL`, which is the exact
-- complement of 065's index. Together the two cover the whole table with no
-- overlap and no gap:
--
--   provider_ref IS NOT NULL  -> uq_mail_responses_provider_ref (065): one row
--                                per provider identifier, forever.
--   provider_ref IS NULL      -> this index: one anonymous row per
--                                (record, channel).
--
--
-- WHAT THIS DELIBERATELY DOES NOT DO — AND IT IS THE OBVIOUS THING.
--
-- It does NOT make (mail_universe_id, channel) unique unconditionally. That was
-- the first draft and it is wrong, because 065's own header says a record may
-- respond more than once and the log must keep every one of them:
--
--   "A record can respond twice (calls the tracked number on Tuesday, hits the
--    PURL on Friday) and the log keeps both while the denormalised pair keeps
--    the most recent."
--
-- An unconditional unique index would make the database REFUSE the second of two
-- genuinely different inbound calls from the same household, and the evidence
-- that somebody rang back would be gone — not flagged, not logged, gone. That is
-- the failure mode 065 spent a paragraph protecting `tracked_number_id` from
-- ("losing the number must not delete the evidence that somebody responded").
-- The escape hatch is deliberate and it is not a workaround: a caller that CAN
-- tell two responses apart passes the identifier it used to tell them apart, and
-- gets two rows.
--
-- It does NOT add a time window ("the same scan within 30 minutes is one
-- response"). There is no source anywhere in this repo, this schema or the
-- vendor material for what that window would be, and a number invented here
-- would be enforced by an index — a guess wearing a constraint's clothing, which
-- is what 065 refused to do for outcome_tier. First anonymous response per
-- record per channel wins, with no clock in the rule at all.
--
-- It does NOT add an index for attributionByCampaign(). Checked before writing:
-- the campaign side is already served by idx_mail_campaign (001_init.sql:362)
-- and idx_mail_universe_campaign_suppressed (065), and the join back from
-- mail_responses is on mail_universe_id, which leads
-- idx_mail_responses_record (065). Adding a third overlapping index would cost
-- write throughput on a bulk load and buy nothing measurable.
--
--
-- RE-RUNNABILITY AND THE EMPTY-TABLE NOTE. IF NOT EXISTS, so a second run is a
-- no-op. `mail_responses` was created by 065 and has had no writer in this repo
-- until src/mail/responses.mjs, so this index is being built over an empty table
-- and cannot fail on pre-existing duplicates. If it ever DOES fail on a real
-- database, that failure is the finding: it means anonymous double-counting has
-- already happened and the duplicates need adjudicating by a human before the
-- constraint goes on. Do not "fix" it by dropping the predicate.

CREATE UNIQUE INDEX IF NOT EXISTS uq_mail_responses_anonymous
  ON mail_responses (mail_universe_id, channel)
  WHERE provider_ref IS NULL;

COMMENT ON INDEX uq_mail_responses_anonymous IS
  'One identifier-less response per (record, channel). Complements uq_mail_responses_provider_ref (065), which covers the rows that DO carry a provider identifier. A caller that can distinguish two responses passes provider_ref and gets two rows; two responses with no identifier at all are indistinguishable and count once. See db/migrations/067_mail_response_idempotency.sql.';
