-- 093_recurring_bills_org_index.sql — give the recurring-bills read an index it
-- can use.
--
-- *** THIS FILE ADDS ONE INDEX. *** No table is altered, no column is added,
-- dropped or renamed, no row is written or deleted. It is additive and safe to
-- re-run: CREATE INDEX IF NOT EXISTS.
--
--
-- WHAT WAS BROKEN.
--
-- src/banking/store.mjs listRecurringBills() is the only read of this table, and
-- it always looks like this:
--
--   SELECT * FROM recurring_bills
--    WHERE org_id = $1
--      AND ($2::uuid IS NULL OR bank_account_id = $2)
--      AND ($3::uuid IS NULL OR client_id = $3)
--      AND ($4 = false OR confidence_label IN ('medium', 'high'))
--    ORDER BY typical_amount_cents ASC, merchant_key ASC
--    LIMIT $5
--
-- `org_id` is the ONLY predicate that is present on every call — the other
-- three are optional and are null by default. 086 shipped three indexes on this
-- table and not one of them leads with org_id:
--
--   uq_recurring_bills_account_merchant_cadence (bank_account_id, merchant_key, cadence)
--   idx_recurring_bills_client                  (client_id, typical_amount_cents) partial
--   idx_recurring_bills_due_confident           (bank_account_id, next_expected_on) partial
--
-- The two partial ones cannot serve the default read at all: it runs with
-- client_id null and confidence unfiltered, which is outside both predicates.
-- So the one filter that is always there had nothing to stand on. Postgres read
-- the whole table, filtered it, sorted the survivors in memory, and only then
-- applied the LIMIT.
--
-- THE PAGE SIZE DID NOT FIX THIS. The LIMIT added for M21 bounds what is SENT
-- back; it does not bound what is READ. One row per account × merchant ×
-- cadence across every client is 36,000 rows for 3,000 clients averaging 12
-- bills each — all of them read and sorted inside a 10-second function budget,
-- to return 500.
--
--
-- WHY THESE THREE COLUMNS, IN THIS ORDER.
--
--   org_id                 first, because it is the equality every call carries.
--   typical_amount_cents   second, and merchant_key third, because they are the
--                          ORDER BY in that order. With the sort columns
--                          following the equality, the planner can walk this
--                          index already in output order and stop after LIMIT
--                          rows instead of reading and sorting the whole org.
--
-- ASC matches the read: the amounts are NEGATIVE by 086's CHECK, so ascending
-- is largest outflow first, which is the order a person reading their own bills
-- wants. Writing the index DESC would defeat the very thing it is here for.
--
--
-- WHY IT IS NOT PARTIAL.
--
-- Every other index on this table carries a WHERE clause, and that is exactly
-- why none of them could serve this read. `presentableOnly` is a parameter, not
-- a constant: the same query runs with confidence filtered and unfiltered, with
-- and without a client, with and without an account. An index that is only
-- valid for one of those shapes is an index the default read cannot touch. This
-- one is unconditional on purpose.
--
--
-- WHY NOT CONCURRENTLY. db/migrate.mjs wraps each file in BEGIN/COMMIT and
-- CREATE INDEX CONCURRENTLY cannot run inside a transaction. This table is
-- young and small; a plain build is a brief write lock on it, not an outage.
-- If it ever gets big enough for that to matter, the concurrent build is a
-- hand-run operation, not a migration.

CREATE INDEX IF NOT EXISTS idx_recurring_bills_org_amount
  ON recurring_bills (org_id, typical_amount_cents, merchant_key);

COMMENT ON INDEX idx_recurring_bills_org_amount IS
  'Serves src/banking/store.mjs listRecurringBills(): org_id is the only always-present filter, and the two trailing columns are its ORDER BY, so a LIMITed read walks the index in order instead of sorting the whole org in memory. Deliberately NOT partial — the confidence, client and account filters are all optional parameters.';
