-- 117_contracts.sql — the contract generator.
--
-- WHY: this platform has had a `documents` registry since 030 with
-- `kind='contract'` and three contract subtypes in its vocabulary, and nothing
-- has ever produced one. A funding agreement is written in somebody's word
-- processor, emailed, signed in an inbox, and lost. There is no record of what
-- wording a client agreed to, no proof it has not been altered since, and no way
-- for either side to fetch a copy back.
--
-- This migration gives contracts a home:
--   contract_templates — the words, with blanks. Edited from a CRM screen, so
--                        changing copy never needs a developer.
--   contracts          — one document sent to one client, with its rendered
--                        words frozen at send and its signature recorded.
--
-- The immutable artifact itself lives in documents/document_versions (030) —
-- this migration does not reimplement that, it points at it. See
-- docs/CONTRACTS-SPEC.md §3 for why the tamper check compares against
-- document_versions.checksum rather than against contracts.body_sha.
--
-- Convention (001_init.sql): org_id, created_at, updated_at on every table,
-- updated_at maintained by the shared set_updated_at() trigger. Rule 7 (org_id
-- everywhere) and Rule 9 (idempotent, replay-safe) both apply.
--
-- DEPENDS ON: 001_init.sql (orgs, clients, staff, set_updated_at()),
-- 030_documents.sql (documents, document_versions), 104_app_role.sql
-- (fundhub_app — the unprivileged role the application connects as).
--
-- NO ROW LEVEL SECURITY. Deliberate, and it matches every table in this
-- repository outside the nineteen partner-isolated ones from 045/046/047/049/050.
-- Access control here is GRANTs (104) plus application-level org scoping in the
-- handlers. Enabling RLS with no policy is DENY-EVERYTHING to an ordinary role —
-- the exact bug 109_no_bare_rls.sql exists to have fixed, which took login down.

-- ---------------------------------------------------------------------------
-- contract_templates — the words, with blanks.
--
-- One row per reusable piece of contract copy. `body` holds {{merge tags}} in
-- the same convention message_templates uses, rendered by the same function
-- (src/lib/render-template.mjs). `manual_fields` names the blanks a staff member
-- types in at send time; those render as {{field.<key>}}.
--
-- NO compliance_passed FLAG, unlike message_templates, and that is a decision
-- rather than an omission. message_templates carries one because sendTemplated
-- fires copy at a client with no human in the loop, so the copy needs a standing
-- approval. Every contract send is a deliberate act by a named staff member who
-- has the fully rendered document on screen in front of them. The human is in
-- the loop on every single send, which is a stronger control than a stored
-- boolean. What replaces it is a narrower write gate: only an owner or an admin
-- may author or edit contract copy at all (api/contracts.mjs).
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS contract_templates (
  id                 uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id             uuid NOT NULL REFERENCES orgs(id),

  -- identity ---------------------------------------------------------------
  -- Never renamed. Same reasoning as message_templates.template_key: a key is
  -- what other code matches on, and a rename that looks safe today becomes a
  -- silent no-op the moment somebody names the old key.
  template_key       text NOT NULL CHECK (template_key ~ '[^[:space:]]'),
  name               text NOT NULL CHECK (name ~ '[^[:space:]]'),

  -- taxonomy — mirrors documents.kind (030). Only the two classes this feature
  -- produces are allowed; invoice_document and deliverable are generated by
  -- other code paths and must not be mintable from a contract template.
  kind               text NOT NULL DEFAULT 'contract'
    CHECK (kind IN ('contract', 'authorization')),
  -- Free text, same posture as documents.subtype: the conventional vocabulary
  -- lives in src/documents/kinds.mjs and extending it must not need a migration.
  subtype            text,

  -- the copy ---------------------------------------------------------------
  body               text NOT NULL CHECK (body ~ '[^[:space:]]'),

  /* manual_fields — the blanks. A JSON ARRAY of objects:
       [{ "key": "loan_amount", "label": "Loan amount", "required": true,
          "help": "Dollars, no comma" }]
     CHECKed as an array so a malformed value cannot reach the screen that
     iterates it. The per-item shape is validated in src/contracts/render.mjs,
     not here — a CHECK strict enough to police object keys would make adding a
     field property a migration. */
  manual_fields      jsonb NOT NULL DEFAULT '[]'::jsonb
    CHECK (jsonb_typeof(manual_fields) = 'array'),

  -- policy ------------------------------------------------------------------
  signature_required boolean NOT NULL DEFAULT true,
  /* The exact sentence printed next to the signing checkbox. Stored per template
     because a soft-pull authorization and a funding agreement do not attest to
     the same thing, and the words a person ticked are the evidence. Copied onto
     the contract at send, frozen there. */
  signature_statement text NOT NULL
    DEFAULT 'I have read this document and I agree to it. Typing my name here is my signature.'
    CHECK (signature_statement ~ '[^[:space:]]'),

  -- lifecycle ---------------------------------------------------------------
  -- Archived, never deleted. Contracts already sent point back at their template.
  active             boolean NOT NULL DEFAULT true,

  -- attribution -------------------------------------------------------------
  -- NOT NULL: an unattributed piece of contract copy is not evidence of
  -- anything, same rule 077 and 099 set for the consent records.
  created_by         uuid NOT NULL REFERENCES staff(id),
  updated_by         uuid REFERENCES staff(id),

  created_at         timestamptz NOT NULL DEFAULT now(),
  updated_at         timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS contract_templates_org_key_uniq
  ON contract_templates (org_id, template_key);
CREATE INDEX IF NOT EXISTS idx_contract_templates_org
  ON contract_templates (org_id, active, kind);

-- ---------------------------------------------------------------------------
-- contracts — one document, sent to one client.
--
-- THE FROZEN COPY IS IN THIS TABLE, and that needs explaining because 030 says
-- the immutable artifact belongs in document_versions.
--
-- It is in BOTH. At send, the rendered bytes go through src/documents/store.mjs
-- and registerDocument(), so document_versions holds them with its checksum
-- immutable by trigger. `rendered_body` here is the copy that is actually SERVED
-- to the signing page, because the object store defaults to the in-memory
-- provider and this repository has no storage vendor configured — bytes put
-- through it do not survive the process, and Netlify functions are stateless.
-- A signing page reading the object store would render blank in production today.
--
-- So: this column is what the client reads, and document_versions.checksum is
-- what proves it has not changed. src/contracts/sign.mjs recomputes the hash of
-- this column at signature time and compares it against that checksum, in
-- constant time. Mismatch = no signature. Two separate tables, with two separate
-- triggers, have to be defeated to alter a contract silently.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS contracts (
  id                  uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id              uuid NOT NULL REFERENCES orgs(id),
  client_id           uuid NOT NULL REFERENCES clients(id),

  -- what was sent ----------------------------------------------------------
  -- RESTRICT by default (no ON DELETE), matching 017/030: deleting a template
  -- must fail rather than orphan the record of what somebody signed.
  template_id         uuid NOT NULL REFERENCES contract_templates(id),
  -- Snapshots, so the record still reads correctly if the template is renamed
  -- in some future that allows renaming, or archived.
  template_key        text NOT NULL,
  title               text NOT NULL CHECK (title ~ '[^[:space:]]'),
  kind                text NOT NULL
    CHECK (kind IN ('contract', 'authorization')),
  subtype             text,

  -- what the staff member typed into the blanks -----------------------------
  merge_values        jsonb NOT NULL DEFAULT '{}'::jsonb
    CHECK (jsonb_typeof(merge_values) = 'object'),

  -- the frozen document -----------------------------------------------------
  rendered_body       text,
  -- 'sha256:<hex>' — same algorithm-prefixed shape as documents.checksum, so
  -- the two are directly comparable without reformatting either.
  body_sha            text
    CHECK (body_sha IS NULL OR body_sha ~ '^[a-z0-9-]+:[0-9a-f]+$'),
  document_id         uuid REFERENCES documents(id),
  document_version_id uuid REFERENCES document_versions(id),
  -- Copied from the template at send. What the signer actually ticked.
  signature_statement text,
  signature_required  boolean NOT NULL DEFAULT true,

  -- status ------------------------------------------------------------------
  status              text NOT NULL DEFAULT 'draft'
    CHECK (status IN ('draft', 'sent', 'viewed', 'signed', 'void')),

  sent_at             timestamptz,
  sent_by             uuid REFERENCES staff(id),
  link_expires_at     timestamptz,
  viewed_at           timestamptz,
  view_count          integer NOT NULL DEFAULT 0 CHECK (view_count >= 0),

  -- the signature -----------------------------------------------------------
  -- No external e-signature vendor, by the brief. What is captured is what a
  -- typed-name signature consists of: the name, the attestation they ticked,
  -- the time, and where from.
  signed_at           timestamptz,
  signer_name         text,
  signer_ip           text,
  signer_user_agent   text,

  voided_at           timestamptz,
  voided_by           uuid REFERENCES staff(id),
  -- A contract cannot be voided into silence. If it is void, somebody said why.
  void_reason         text,

  created_by          uuid NOT NULL REFERENCES staff(id),
  created_at          timestamptz NOT NULL DEFAULT now(),
  updated_at          timestamptz NOT NULL DEFAULT now(),

  -- Shape rules the status column alone cannot express -----------------------
  -- A draft has no frozen body; anything past draft has one.
  CONSTRAINT contracts_sent_has_body_ck CHECK (
    status = 'draft'
    OR (rendered_body IS NOT NULL AND body_sha IS NOT NULL AND sent_at IS NOT NULL)),
  -- A signature is a name AND a time, never one without the other.
  CONSTRAINT contracts_signature_pair_ck CHECK (
    (signed_at IS NULL AND signer_name IS NULL)
    OR (signed_at IS NOT NULL AND signer_name IS NOT NULL
        AND signer_name ~ '[^[:space:]]')),
  CONSTRAINT contracts_signed_status_ck CHECK (
    signed_at IS NULL OR status = 'signed'),
  CONSTRAINT contracts_void_reason_ck CHECK (
    voided_at IS NULL OR (void_reason IS NOT NULL AND void_reason ~ '[^[:space:]]')),
  CONSTRAINT contracts_void_status_ck CHECK (
    voided_at IS NULL OR status = 'void')
);

CREATE INDEX IF NOT EXISTS idx_contracts_org         ON contracts (org_id, status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_contracts_client      ON contracts (org_id, client_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_contracts_template    ON contracts (template_id);
CREATE INDEX IF NOT EXISTS idx_contracts_document    ON contracts (document_id) WHERE document_id IS NOT NULL;
-- The CRM's "waiting on a signature" queue.
CREATE INDEX IF NOT EXISTS idx_contracts_outstanding ON contracts (org_id, sent_at DESC)
  WHERE status IN ('sent', 'viewed');

-- ---------------------------------------------------------------------------
-- Never delete. Same posture as 016_ledger_no_delete.sql and 030_documents.sql.
--
-- A signed contract that a stray DELETE can remove is not evidence of anything,
-- and a template that can vanish takes the meaning of every contract pointing at
-- it. Archive a template (active = false) and void a contract instead.
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION contracts_no_delete() RETURNS trigger AS $$
BEGIN
  RAISE EXCEPTION
    'contracts %: contracts are never deleted — void it instead', OLD.id;
  RETURN NULL;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_contracts_no_delete ON contracts;
CREATE TRIGGER trg_contracts_no_delete
  BEFORE DELETE ON contracts
  FOR EACH ROW EXECUTE FUNCTION contracts_no_delete();

CREATE OR REPLACE FUNCTION contract_templates_no_delete() RETURNS trigger AS $$
BEGIN
  RAISE EXCEPTION
    'contract_templates %: templates are never deleted — set active = false instead',
    OLD.id;
  RETURN NULL;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_contract_templates_no_delete ON contract_templates;
CREATE TRIGGER trg_contract_templates_no_delete
  BEFORE DELETE ON contract_templates
  FOR EACH ROW EXECUTE FUNCTION contract_templates_no_delete();

-- ---------------------------------------------------------------------------
-- Once sent, the document is frozen. Once signed, the signature is too.
--
-- Without this, "the words cannot change after sending" is a comment in an
-- application file. src/contracts/sign.mjs's hash comparison would still catch
-- a tampered body at signature time — but only at signature time, and only for
-- an unsigned contract. This closes the window and covers the already-signed
-- case, which is the one an auditor actually asks about.
--
-- The lifecycle columns stay writable, because that is what a status is for: a
-- contract legitimately goes sent → viewed → signed, and view_count climbs.
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION contracts_frozen_after_send() RETURNS trigger AS $$
BEGIN
  IF OLD.status <> 'draft' THEN
    IF NEW.rendered_body       IS DISTINCT FROM OLD.rendered_body
       OR NEW.body_sha         IS DISTINCT FROM OLD.body_sha
       OR NEW.document_id      IS DISTINCT FROM OLD.document_id
       OR NEW.document_version_id IS DISTINCT FROM OLD.document_version_id
       OR NEW.template_id      IS DISTINCT FROM OLD.template_id
       OR NEW.client_id        IS DISTINCT FROM OLD.client_id
       OR NEW.org_id           IS DISTINCT FROM OLD.org_id
       OR NEW.merge_values     IS DISTINCT FROM OLD.merge_values
       OR NEW.signature_statement IS DISTINCT FROM OLD.signature_statement
       OR NEW.sent_at          IS DISTINCT FROM OLD.sent_at
    THEN
      RAISE EXCEPTION
        'contracts %: this contract has been sent — its wording is frozen and cannot be changed',
        OLD.id;
    END IF;
  END IF;

  IF OLD.signed_at IS NOT NULL THEN
    IF NEW.signed_at         IS DISTINCT FROM OLD.signed_at
       OR NEW.signer_name    IS DISTINCT FROM OLD.signer_name
       OR NEW.signer_ip      IS DISTINCT FROM OLD.signer_ip
       OR NEW.signer_user_agent IS DISTINCT FROM OLD.signer_user_agent
       OR NEW.status         IS DISTINCT FROM OLD.status
    THEN
      RAISE EXCEPTION
        'contracts %: this contract is signed — the signature and its status cannot be changed',
        OLD.id;
    END IF;
  END IF;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_contracts_frozen ON contracts;
CREATE TRIGGER trg_contracts_frozen
  BEFORE UPDATE ON contracts
  FOR EACH ROW EXECUTE FUNCTION contracts_frozen_after_send();

-- ---------------------------------------------------------------------------
-- updated_at (001_init.sql convention)
-- ---------------------------------------------------------------------------
DROP TRIGGER IF EXISTS contract_templates_updated_at ON contract_templates;
CREATE TRIGGER contract_templates_updated_at
  BEFORE UPDATE ON contract_templates
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS contracts_updated_at ON contracts;
CREATE TRIGGER contracts_updated_at
  BEFORE UPDATE ON contracts
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ---------------------------------------------------------------------------
-- Grants for the unprivileged application role (104_app_role.sql).
--
-- 104 sets ALTER DEFAULT PRIVILEGES so future tables are granted automatically,
-- but that only applies to objects created by the role that set it. Migrations
-- may be applied by a different owner (MIGRATION_DATABASE_URL), so these are
-- explicit rather than assumed. Guarded, because a database that has never run
-- 104 — a throwaway CI container — has no such role and must not fail here.
--
-- DELETE is granted for consistency with every other table and is inert: both
-- tables block DELETE with a trigger above, which a GRANT cannot override.
-- ---------------------------------------------------------------------------
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'fundhub_app') THEN
    GRANT SELECT, INSERT, UPDATE, DELETE ON contract_templates TO fundhub_app;
    GRANT SELECT, INSERT, UPDATE, DELETE ON contracts TO fundhub_app;
  ELSE
    RAISE NOTICE 'skipped grants: role fundhub_app does not exist in this database';
  END IF;
END $$;

COMMENT ON TABLE contract_templates IS
  'Reusable contract copy with {{merge tags}}, edited from the CRM. Changing wording never needs code.';
COMMENT ON TABLE contracts IS
  'One contract sent to one client. rendered_body is frozen at send; document_versions.checksum is what proves it.';
COMMENT ON COLUMN contracts.body_sha IS
  'sha256 of rendered_body at send. The tamper check compares a fresh hash of rendered_body against document_versions.checksum — see docs/CONTRACTS-SPEC.md section 3.';
