-- 118_sms_routing_twilio.sql — DELIBERATELY DOES NOTHING. Read before deleting.
--
-- ═══════════════════════════════════════════════════════════════════════════
-- THIS FILE IS THE RECORD OF A CHANGE THAT WAS WRITTEN AND THEN WITHDRAWN.
--
-- The owner said, 2026-08-02: "We're gonna be using Twilio. GHL is just a patch
-- for now." The first version of this migration acted on that directly — it
-- UPDATEd message_channel_routing to point sms at twilio. That was wrong, and
-- the reason is worth keeping where the next person to have the same idea will
-- find it.
--
--
-- WHY IT WAS WITHDRAWN: A2P 10DLC.
--
-- US carriers require business texting traffic to be registered under A2P 10DLC
-- — a brand and a campaign, approved per sending number. Unregistered A2P
-- traffic is not rejected loudly; it is FILTERED, quietly, by the carriers,
-- with delivery receipts that often still say "sent". A staff reply would
-- disappear somewhere between here and the customer's phone and nothing in this
-- system would know.
--
-- Three separate places in this repository already say the registration lives
-- on the GHL side and that Twilio waits for it:
--
--   src/messaging/providers/ghl-relay.mjs   "the cutover ... leaves SMS running
--     through it, because the numbers, the A2P 10DLC registration and the
--     conversation threads all live there"
--   src/messaging/providers/twilio.mjs      "the SMS provider that replaces the
--     GHL relay ONCE A2P 10DLC CLEARS", and ENABLED = false
--   src/messaging/providers/providers.test.mjs "twilio has to sit built and
--     unrouted until A2P 10DLC clears"
--
-- Whether that registration has cleared is a fact about a Twilio account and a
-- carrier queue. It is not in this database, not in this repository, and not
-- something an agent may assume. "We're going to use Twilio" is a direction; it
-- is not "the registration is approved, flip it tonight". A migration runs on
-- deploy, unattended, so encoding that assumption here would move live customer
-- texting onto an unverified route with no human present at the moment it
-- happened.
--
--
-- ═══════════════════════════════════════════════════════════════════════════
-- *** THE PROBLEM THAT PROMPTED THIS IS REAL AND IS NOT FIXED. ***
--
-- The GHL relay addresses a text by `clients.ghl_contact_id` — see its
-- ADDRESS_FIELD. 001_init.sql describes that column as a "legacy key: migration
-- + parallel-run resolve": it is populated for contacts imported from the old
-- system and is NULL for anybody created in this platform since.
--
-- So a staff member replying to a client who never existed in GHL gets
-- OUTCOME.NO_ADDRESS — "the client has no ghl_contact_id to send to" —
-- permanently, with no retry that can ever succeed. The reply inbox works for
-- imported customers and cannot text newer ones.
--
-- HOW TO SEE WHETHER THAT BITES YOU, one query, no writes:
--
--   SELECT count(*) FILTER (WHERE ghl_contact_id IS NULL) AS cannot_be_texted,
--          count(*) AS total
--     FROM clients;
--
-- If `cannot_be_texted` is 0, texting works today and the switch below is not
-- urgent. If it is not 0, that many customers cannot receive a text reply until
-- either the switch happens or those contact ids are backfilled.
--
--
-- ═══════════════════════════════════════════════════════════════════════════
-- THE SWITCH, FOR WHOEVER RUNS IT WHEN A2P HAS CLEARED.
--
-- It is one statement, it is reversible, and it belongs to a human who knows
-- the registration is approved:
--
--   UPDATE message_channel_routing SET provider = 'twilio' WHERE channel = 'sms';
--
-- Three environment variables must be set FIRST or every text fails loudly
-- (which is the correct direction, and the provider names the missing ones):
--
--   TWILIO_SEND_ACCOUNT_SID   the "AC..." account id
--   TWILIO_SEND_AUTH_TOKEN    the auth token — set with --secret
--   TWILIO_SEND_FROM          an E.164 number, or the "MG..." Messaging Service
--                             SID, which is the usual shape under A2P
--
-- These are vendor credentials issued by Twilio. CLAUDE.md §11's "generate a
-- strong random value" rule is for secrets this system mints and cannot apply
-- to a token another company issues.
--
-- NOTE the separate, already-existing TWILIO_AUTH_TOKEN: that one verifies
-- INBOUND webhook signatures and is a different value. One variable serving both
-- directions is how a rotated sending credential silently breaks inbound
-- receipt. Do not consolidate them.
--
-- Also flip `ENABLED` in src/messaging/providers/twilio.mjs to true and
-- ghl-relay.mjs to false in the same change — providers.test.mjs asserts the
-- code's idea of the default matches the database's, and will fail until it
-- does. That test failing is the feature: it is what stops the two drifting.
--
--
-- WHY A FILE AT ALL, RATHER THAN NOTHING.
--
-- Migration numbers are permanent — db/expected-migrations.mjs and
-- schema_migrations key on the filename, and 118 has been applied in at least
-- one environment already. Deleting it makes health-migrations disagree with
-- reality. And the reasoning above is the kind that gets rediscovered the
-- expensive way. A no-op with an explanation costs one row in a table.
SELECT 1 WHERE false;
