-- 122_conversations_activity.sql — the index the inbox list sorts on.
--
-- ═══════════════════════════════════════════════════════════════════════════
-- WHAT THIS IS FOR.
--
-- api/read/inbox.mjs picks its page with
--
--   WHERE org_id = $1
--   ORDER BY COALESCE(last_pulse_at, created_at) DESC, id DESC
--   LIMIT 51
--
-- and this is the index that serves it. Without it, every inbox load sorts the
-- company's entire conversations table to return fifty rows. That is invisible
-- at a few hundred threads and is the reason the screen stops loading at a
-- hundred thousand.
--
-- IT INDEXES THE EXPRESSION, NOT THE COLUMNS. `COALESCE(last_pulse_at,
-- created_at)` is what the query orders by, so that is what has to be indexed —
-- an index on `last_pulse_at` alone cannot serve it, because Postgres cannot
-- know the COALESCE is monotonic in it. The expression here and the ORDER BY
-- there must stay character-for-character equivalent or the index is quietly
-- unused and everything still works, just slowly. That is the failure mode
-- worth naming: a wrong index does not break anything, it just stops helping,
-- and nobody notices until the table is large.
--
-- DESC NULLS LAST matches the query's own ordering. COALESCE means the
-- expression is only NULL if BOTH columns are, and created_at is NOT NULL, so
-- in practice there are no NULLs — the clause is there so the index and the
-- query state the same thing rather than relying on that staying true.
--
-- `id DESC` is the tiebreaker, included so the ordering is total. Two threads
-- with identical activity times would otherwise come back in whatever order the
-- heap produced, which makes OFFSET paging skip and repeat rows.
--
-- NOT partial and not filtered: every conversation row is a candidate for its
-- own company's inbox, so there is no subset to narrow to.
CREATE INDEX IF NOT EXISTS idx_conversations_activity
  ON conversations (org_id, (COALESCE(last_pulse_at, created_at)) DESC NULLS LAST, id DESC);

-- ── the "needs reply" filter's other half ───────────────────────────────────
--
-- The tab asks, per candidate thread, "what direction is the newest message on
-- it". That is served by idx_messages_thread from 117 — (conversation_id,
-- created_at DESC) — which already exists and needs nothing added.
--
-- `direction` is deliberately NOT added to it. Including it would make the
-- lookup index-only for this one query, at the cost of a wider index on the
-- table that grows fastest in the system, to save a single heap fetch on a
-- query that already stops after fifty rows. If a query plan ever says
-- otherwise, that is the moment to add it — with the plan attached.
