// The journeys generator, and the guard that stops these pages going stale.
//
// Lives under scripts/ because npm test's glob is "src/**" and "scripts/**" ONLY
// — CLAUDE.md §12's first trap. A test anywhere else silently never runs.
//
// THE TEST THAT MATTERS IS "not stale". It is the whole reason a generator was
// written instead of eight hand-written files: adding a route or changing a role
// gate fails the suite until the journeys are regenerated. Documentation that
// drifts without anyone noticing is the failure mode, and for these pages it is
// worse than a stale diagram, because a stale journey makes a false claim about
// who can reach a client's data.
//
// No database and no DATABASE_URL. Everything here reads source files.

import { test, describe } from "node:test";
import assert from "node:assert";
import fs from "node:fs";
import path from "node:path";

import { build, stale, OUT_DIR } from "./generate.mjs";
import { extractAll, routes, roleSets, code, gateFor, JOURNEYS, REPO } from "./extract.mjs";

const data = extractAll();
const files = build();

describe("the journeys are not stale", () => {

  test("*** every generated page matches what the code now produces ***", () => {
    const bad = stale(files);
    assert.deepEqual(bad, [],
      "docs/journeys is out of date with the code:\n" +
      bad.map((b) => `  ${b.reason.padEnd(8)} docs/journeys/${b.rel}`).join("\n") +
      "\n\nRun `npm run journeys` and commit the result.");
  });

  test("every tracked journey has a page, and the index lists them all", () => {
    for (const j of JOURNEYS) {
      assert.ok(files[`${j.name}-actual.md`], `no page generated for the tracked journey "${j.name}"`);
    }
    assert.ok(files["README.md"]);
    const readme = files["README.md"];
    for (const j of JOURNEYS) {
      assert.ok(readme.includes(`${j.name}-actual.md`), `${j.name} is missing from the index`);
    }
  });

  test("the generator itself never authors an -intended.md", () => {
    // CLAUDE.md §4: intended journeys are hand-authored and agents do not edit
    // them. An agent writing one would be authoring the source of truth it is
    // meant to be checked against. That still holds for `npm run journeys` —
    // build() below is the generator's own output, and it must stay limited to
    // `-actual.md` and the README no matter what exists on disk.
    for (const name of Object.keys(files)) {
      assert.ok(!/-intended\.md$/.test(name), `the generator produced ${name}; it must never author an intended journey`);
    }
  });

  test("every -intended.md on disk (if any) says plainly it was written after the fact", () => {
    // From 2026-07-31 to 2026-08-02 none existed, by the owner's decision (see
    // the prior version of this test and docs/journeys/README.md's history). On
    // 2026-08-02 the owner directed a one-time, explicit exception: each one was
    // generated from the same extracted data as its -actual.md, because no
    // independent spec existed to draw intent from otherwise. This test does not
    // require they exist — a human replacing one with real, independently
    // authored intent is the intended end state — but any that DO exist must
    // carry the disclaimer, so nobody mistakes a stopgap for a settled spec.
    if (!fs.existsSync(OUT_DIR)) return;
    const intendedFiles = fs.readdirSync(OUT_DIR).filter((f) => /-intended\.md$/.test(f));
    for (const name of intendedFiles) {
      const body = fs.readFileSync(path.join(OUT_DIR, name), "utf8");
      assert.match(body, /WRITTEN AFTER THE FACT, NOT BEFORE IT/,
        `${name} exists but does not carry the after-the-fact disclaimer`);
    }
  });

  test("every page says it is generated, so nobody hand-edits one", () => {
    for (const [name, body] of Object.entries(files)) {
      assert.match(body, /GENERATED by scripts\/journeys\/generate\.mjs/, `${name} has no generated-by stamp`);
    }
  });

  test("Mermaid is inside a ```mermaid fence in a .md file, or GitHub will not render it", () => {
    for (const [name, body] of Object.entries(files)) {
      if (!body.includes("flowchart")) continue;
      assert.match(body, /```mermaid\nflowchart TD/, `${name} has a flowchart that is not in a mermaid fence`);
      assert.ok(name.endsWith(".md"), `${name} must be .md — a .mermaid file does not render`);
      // Every opened fence is closed.
      assert.equal((body.match(/```/g) || []).length % 2, 0, `${name} has an unbalanced code fence`);
    }
  });
});

describe("the extraction is faithful to the code", () => {

  test("the routing table was actually parsed — not silently empty", () => {
    // THE REGRESSION THIS FILE EXISTS FOR. The first version of code() stripped
    // block comments BEFORE line comments. netlify/functions/api.mjs contains
    // the line `// One function serves every /api/* path`, and the `/*` inside
    // `/api/*` opened a block comment that swallowed every import in the file.
    // The extractor did not crash — it reported 48 routes with "handler file ?
    // not found on disk" and would have produced eight confidently wrong pages.
    const r = routes();
    assert.ok(r.length > 20, `only ${r.length} routes parsed — the ROUTES map did not parse`);
    const noFile = r.filter((x) => !x.file);
    assert.deepEqual(noFile.map((x) => x.key), [],
      "these ROUTES entries did not resolve to a handler file, which usually means the " +
      "import parsing broke rather than that the handlers are missing");
  });

  test("code() survives a // line containing /* — the exact trap above", () => {
    const src = [
      "// One function serves every /api/* path (config.path below).",
      'import a from "../../api/a.mjs";',
      "const real = 1;"
    ].join("\n");
    const out = code(src);
    assert.match(out, /import a from/, "the import was eaten by a fake block comment");
    assert.match(out, /const real = 1/);
  });

  test("code() still strips real block comments, including gate-shaped prose", () => {
    // api/read/tradelines.mjs's header quotes the BROKEN `{ roles: ROLE_SETS.STAFF }`
    // call that once shipped. Reading that comment as the gate would report the
    // opposite of the truth.
    const src = [
      "/* requireAuth(req, res, { roles: ROLE_SETS.STAFF }) was the bug. */",
      "const real = 1;"
    ].join("\n");
    const out = code(src);
    assert.ok(!/ROLE_SETS\.STAFF/.test(out), "prose describing a gate must not be read as a gate");
  });

  test("ROLE_SETS resolved to real role names, not to the constant's name", () => {
    const sets = roleSets();
    assert.ok(sets.STAFF && sets.STAFF.includes("closer"), "ROLE_SETS.STAFF did not resolve");
    assert.ok(sets.FINANCE && sets.FINANCE.includes("owner"));
    for (const [name, roles] of Object.entries(sets)) {
      assert.ok(roles.length > 0, `${name} resolved to an empty set`);
      for (const r of roles) assert.match(r, /^[a-z_]+$/, `${name} contains a suspicious role "${r}"`);
    }
  });

  test("*** no route's gate is left unverified ***", () => {
    // Not a style point. An unverified gate means this documentation cannot say
    // who reaches that route — and an endpoint nobody can characterise is exactly
    // where a hole hides. If this ever fails, the pages will say UNVERIFIED
    // rather than guess, but somebody has to look.
    const unverified = data.endpoints.filter((e) => e.gate.kind === "unverified");
    assert.deepEqual(unverified.map((e) => `${e.key}: ${e.gate.note}`), [],
      "these routes' gates could not be traced from the code");
  });

  test("a signature-verified route is never described as reachable by anyone", () => {
    // The dangerous direction. /api/webhooks/:provider has no requireAuth, and an
    // earlier version of the renderer printed "anyone" for it. Anyone can CALL it;
    // a caller without the provider's signature is refused.
    const verified = data.endpoints.filter((e) => e.gate.kind === "verified-other");
    assert.ok(verified.length > 0, "expected at least the webhook and signed-link routes");
    for (const e of verified) {
      assert.ok(e.gate.verifiedBy, `${e.key} is verified-other with no mechanism named`);
      for (const [name, body] of Object.entries(files)) {
        const row = body.split("\n").find((l) => l.startsWith(`| \`/api/${e.key}\``));
        if (!row) continue;
        assert.ok(!/\|\s*anyone\s*\|/.test(row),
          `${name} describes /api/${e.key} as reachable by "anyone", but it is verified by ${e.gate.verifiedBy}`);
      }
    }
  });

  test("readHandler endpoints that name principals also admit staff", () => {
    // src/http/read-api.mjs:194 calls requirePrincipal(req, res, ["staff", ...principals]).
    // Reading only the declared list would show these as closed to employees.
    const withPrincipals = data.endpoints.filter(
      (e) => e.gate.kind === "role-set" && e.gate.principals);
    assert.ok(withPrincipals.length > 0, "expected at least read/entitlements and read/partners");
    for (const e of withPrincipals) {
      assert.ok(e.gate.principals.includes("staff"),
        `${e.key} declares principals without staff; readHandler always prepends it`);
    }
  });

  test("the two different requireRole functions are not confused", () => {
    // read-api.mjs's requireRole has NO super-role; middleware/requireRole.mjs has
    // SUPER_ROLES = ["owner"]. /api/inquiry uses the second, so owner reaches it
    // without being named in the call. Reporting only the named roles would
    // understate who gets in.
    const inquiry = data.endpoints.find((e) => e.key === "inquiry");
    assert.ok(inquiry, "/api/inquiry vanished from the routing table");
    assert.ok(inquiry.gate.roles.includes("owner"),
      "owner reaches /api/inquiry via SUPER_ROLES and must be listed");
    assert.ok(inquiry.gate.roles.includes("inquiry_specialist"));
    assert.equal(data.superRoleOnReadPath, false,
      "read-api.mjs gained a SUPER_ROLES — the README's claim that there is no implicit " +
      "super-role on the read path is now wrong and must be updated");
  });

  test("a role journey only reaches routes whose set names that role", () => {
    const closer = JOURNEYS.find((j) => j.name === "role-closer");
    const financeOnly = data.endpoints.find((e) => e.key === "read/commissions");
    assert.ok(financeOnly, "read/commissions vanished");
    /* sales_manager joined ROLE_SETS.FINANCE on 2026-08-01 by owner decision
       (H-6 in Ticket 8): company-wide commission visibility. The point of this
       test is unchanged — a CLOSER must still not reach the commissions read —
       so the expectation is widened, not the assertion below it weakened. */
    assert.deepEqual(financeOnly.gate.roles, ["owner", "admin", "sales_manager"]);
    assert.ok(!financeOnly.gate.roles.includes("closer"));

    const body = files["role-closer-actual.md"];
    const blockedSection = body.slice(body.indexOf("## What they are blocked from"));
    assert.ok(blockedSection.includes("`/api/read/commissions`"),
      `a ${closer.subject} must not be shown reaching the commissions read`);
  });
});

describe("nothing is invented", () => {

  /* ═══════════════════════════════════════════════════════════════════════
     THESE THREE TESTS WERE INVERTED ON 2026-08-01, AND WHY MATTERS.

     They used to assert that sales_manager did NOT exist: no flowchart on the
     page, the page saying "no such role", and a walk of src/, api/ and db/
     failing if the string appeared anywhere. That was the right guard for the
     owner's 2026-07-31 decision — the role was planned, not built, and no
     agent was to create it ON ITS OWN INITIATIVE.

     The owner directed the build in Ticket 8 on 2026-08-01, stating the
     resolution explicitly: "The correct resolution is to build the role, not
     to remove it from the editor." So the guard's premise is spent. It is
     INVERTED RATHER THAN DELETED — the same three places are still checked,
     but now for consistency instead of absence, so a half-finished job is
     still caught. Deleting them would have removed the only thing watching
     this role.
     ═══════════════════════════════════════════════════════════════════════ */

  test("*** role-sales-manager is now drawn, because the role exists ***", () => {
    const page = files["role-sales-manager-actual.md"];
    assert.ok(page, "the tracked journey has no page at all");
    assert.ok(!/no such role/i.test(page),
      "the role was built — the page must stop saying it does not exist");
    assert.ok(page.includes("flowchart"),
      "a real role gets a real diagram, same as every other role journey");
  });

  test("the page records that the role was built, and on whose instruction", () => {
    // The 2026-07-31 decision is superseded, not forgotten. Whoever reads this
    // page next should be able to see that the reversal was directed, not an
    // agent deciding for itself.
    const page = files["role-sales-manager-actual.md"];
    assert.ok(!/[Dd]o not build it yet/.test(page),
      "the page still carries the superseded instruction not to build it");
    assert.ok(!/FUTURE WORK/.test(page),
      "the role is built — it is no longer future work");
  });

  test("the role is wired everywhere, not half-built", () => {
    /* The inverse of the old guard. It used to fail if `sales_manager`
       appeared anywhere under src/, api/ or db/; it now fails if any of the
       places that MUST carry it does not. A partial job — the role set widened
       but no catalog row, or a shell entry with no demo login — is exactly
       what src/auth/role-catalog-drift.pg.test.mjs catches at run time, and
       this catches the file-level half of it without needing a database. */
    const must = [
      ["src/http/read-api.mjs", "ROLE_SETS.STAFF and ROLE_SETS.FINANCE"],
      ["src/lib/create-task.mjs", "the task-routing role set"],
      ["src/auth/demo-roster.mjs", "the demo login roster"],
      ["src/auth/seed-role-accounts.mjs", "the role-test roster"],
      ["db/migrations/112_sales_manager_role.sql", "the catalog row and task CHECK"]
    ];
    const missing = must.filter(([rel]) =>
      !/sales_manager/.test(fs.readFileSync(path.join(REPO, rel), "utf8")));
    assert.deepEqual(missing.map(([rel, what]) => `${rel} (${what})`), [],
      "sales_manager is built but not wired everywhere — a role missing from one of " +
      "these is a role that silently does nothing in that layer");

    // public/app/shell.js is not a .mjs under src/api/db, so it is checked here
    // rather than by the walk: a role with no ROLE_TABS entry signs in and
    // bounces to the shared staff tabs.
    const shell = fs.readFileSync(path.join(REPO, "public/app/shell.js"), "utf8");
    // ROLE_TABS value is the resolver key ("sales_manager"), not the old
    // blanket "staff" string — allowedFor() adds SALES_FLOOR_ONLY on top.
    assert.match(shell, /sales_manager:\s*"(?:staff|sales_manager)"/,
      "shell.js ROLE_TABS has no sales_manager row");
    assert.match(shell, /sales_manager:\s*"sales-floor\.html"/, "shell.js HOME has no sales_manager landing screen");
  });

  test("every journey names the code that establishes what it maps to", () => {
    // Two of these mappings are not obvious from the name — white-label is the
    // `partner` kind, and the Inquiry Remover screen is the `inquiry_specialist`
    // role. A reader must be able to check the mapping rather than trust it.
    for (const j of JOURNEYS) {
      assert.ok(j.evidence && j.evidence.length > 20, `${j.name} has no evidence for its mapping`);
      if (j.missing) continue;
      assert.match(files[`${j.name}-actual.md`], /Who this is, in the code/);
    }
  });

  test("the pages never claim a route exists that is not in the routing table", () => {
    const known = new Set(data.endpoints.map((e) => `/api/${e.key}`));
    for (const [name, body] of Object.entries(files)) {
      for (const m of body.matchAll(/\| `(\/api\/[^`]+)`/g)) {
        assert.ok(known.has(m[1]), `${name} lists ${m[1]}, which is not in the routing table`);
      }
    }
  });
});
