// Turn the extracted facts into the journey pages a non-coder can read.
//
// CLAUDE.md §10: the person these are for does not read code. So every page
// answers three questions in plain words — who is this, what can they actually
// do, and what are they stopped from doing — and the Mermaid picture carries the
// shape while the table carries the detail.
//
// MERMAID GOES IN A ```mermaid FENCE INSIDE A .md FILE. A standalone .mermaid
// file does not render on GitHub, which CLAUDE.md §4 calls out explicitly.
//
// NOTHING IS INVENTED HERE. This module only formats what extract.mjs found. If
// a gate came back unverified it is rendered as UNVERIFIED, in the diagram and
// in the table, rather than quietly dropped to keep the picture tidy.

import { reaches } from "./extract.mjs";

const STAMP = "<!-- GENERATED by scripts/journeys/generate.mjs — do not edit by hand. Run `npm run journeys`. -->";

/* Mermaid node text cannot contain unescaped quotes, brackets or parentheses.
   Route keys are plain, but the gate notes are prose and do contain them. */
const mm = (s) => String(s).replace(/["`]/g, "").replace(/[[\]{}()]/g, "").replace(/\n/g, " ").trim();

/* The first path segment, which is how a reader thinks about these — "the
   hiring screens", "the campaign screens" — rather than 51 individual routes. */
function area(key) {
  const head = key.split("/")[0];
  return key.includes("/") ? head : "top level";
}

const AREA_LABEL = {
  "read": "Reading data",
  "dashboard": "The dashboard",
  "campaigns": "Campaigns",
  "creative": "Creative Factory",
  "hiring": "Hiring",
  "auth": "Signing in and out",
  "finance": "Finance",
  "webhooks": "Incoming webhooks",
  "documents": "Documents",
  "top level": "Everything else"
};

const label = (a) => AREA_LABEL[a] || a;

/* "a affiliate" reads as a typo and undermines a page whose whole job is being
   trusted about who can reach what. */
const an = (w) => (/^[aeiou]/i.test(String(w)) ? "an" : "a");

function groupByArea(endpoints) {
  const groups = new Map();
  for (const e of endpoints) {
    const a = area(e.key);
    if (!groups.has(a)) groups.set(a, []);
    groups.get(a).push(e);
  }
  return [...groups.entries()].sort((x, y) => (x[0] < y[0] ? -1 : 1));
}

/* ---------------------------------------------------------------------------
   The diagram
   ------------------------------------------------------------------------ */

function diagram(journey, allowed, refused, unverified, specificCount) {
  const lines = [
    "```mermaid",
    "flowchart TD",
    `    START([${mm(journey.name)} arrives]) --> AUTH{Signed in?}`,
    "    AUTH -->|No| OUT[Refused — 401 not signed in]",
    `    AUTH -->|Yes| WHO{Recognised as ${mm(journey.subject)}?}`,
    "    WHO -->|No| DENY[Refused — 403 forbidden]"
  ];

  if (specificCount === 0) {
    lines.push("    WHO -->|Yes| NONE[Nothing admits this one — every endpoint refuses them]");
    lines.push("    NONE --> OPENONLY[Only the routes anyone can reach without signing in]");
  } else if (!allowed.length) {
    lines.push("    WHO -->|Yes| NONE[Reaches nothing — every route refuses this one]");
  } else {
    lines.push("    WHO -->|Yes| CAN[Can reach]");
    for (const [a, list] of groupByArea(allowed)) {
      const id = "A_" + a.replace(/[^a-z0-9]/gi, "_");
      lines.push(`    CAN --> ${id}[${mm(label(a))} — ${list.length} route${list.length === 1 ? "" : "s"}]`);
    }
  }

  if (refused.length) {
    const byArea = groupByArea(refused);
    lines.push(`    WHO -->|Yes| CANT[Blocked — ${refused.length} route${refused.length === 1 ? "" : "s"}]`);
    for (const [a, list] of byArea) {
      const id = "B_" + a.replace(/[^a-z0-9]/gi, "_");
      lines.push(`    CANT --> ${id}[${mm(label(a))} — ${list.length} blocked]`);
    }
  }

  if (unverified.length) {
    lines.push(`    WHO -->|Yes| UNV[UNVERIFIED — ${unverified.length} route${unverified.length === 1 ? "" : "s"} whose gate could not be traced]`);
  }

  lines.push("```");
  return lines.join("\n");
}

/* ---------------------------------------------------------------------------
   The tables
   ------------------------------------------------------------------------ */

/* WHO THE CODE LETS IN, said accurately.
   An earlier version printed only the role list, which made two different lies
   possible: a route open to clients showed nothing but staff roles, and a
   signature-verified webhook showed "anyone". Roles and principal kinds are
   different axes and both get printed when both apply. */
function who(gate) {
  if (gate.kind === "verified-other") return `**not a sign-in** — ${gate.verifiedBy}`;
  if (gate.kind === "open") return "anyone";

  const kinds = (gate.principals || []).filter((k) => k !== "staff");
  const roles = gate.roles ? gate.roles.join(", ") : null;

  if (roles && kinds.length) return `employees: ${roles}<br>plus: ${kinds.join(", ")}`;
  if (roles) return roles;
  if (gate.principals) return gate.principals.join(", ");
  return "—";
}

function table(rows) {
  if (!rows.length) return "_None._";
  const out = [
    "| Route | Methods | Who the code lets in |",
    "|---|---|---|"
  ];
  for (const e of rows) {
    out.push(`| \`/api/${e.key}\` | ${e.methods.length ? e.methods.join(", ") : "—"} | ${who(e.gate)} |`);
  }
  return out.join("\n");
}

/* ---------------------------------------------------------------------------
   One journey page
   ------------------------------------------------------------------------ */

function page(journey, data) {
  const { endpoints } = data;

  if (journey.missing) {
    return [
      STAMP,
      "",
      `# ${journey.name} — actual`,
      "",
      "## This journey has nothing behind it",
      "",
      "**There is no such role in this system.** `CLAUDE.md` §4 lists `role-sales-manager`",
      "as a tracked journey, and nothing in `src/`, `api/` or `db/` defines a sales-manager",
      "role. It is not a role with no permissions — the name does not appear at all.",
      "",
      "The staff roles that do exist:",
      "",
      "```",
      "owner, admin, funding_advisor, closer, inquiry_specialist, setter, partner",
      "```",
      "",
      "> Source: `src/http/read-api.mjs` (`ROLE_SETS`), `db/schema/001_init.sql` (`staff.role`),",
      "> `db/migrations/036_partner_role.sql`.",
      "",
      "No diagram is drawn here. Drawing one would mean inventing a journey, and a made-up",
      "picture of who can do what is worse than an empty page — somebody would plan against it.",
      "",
      "## Owner decision, 2026-07-31 — this is FUTURE WORK",
      "",
      "**The role is planned, not dropped.** Sarah runs sales. `role-sales-manager` stays",
      "listed in `CLAUDE.md` §4 as a tracked journey, and the absence of the role in the code",
      "is a to-do rather than a stale entry to clean up.",
      "",
      "**Do not build it yet.** No agent should create a `sales_manager` role, add it to a",
      "`ROLE_SETS` value, or write endpoints for it on its own initiative. When somebody does",
      "build it, this page starts drawing itself — nothing here needs editing by hand.",
      "",
      "Recorded on the board at `docs/workflows/pii-and-journeys.md`.",
      ""
    ].join("\n");
  }

  const scored = endpoints.map((e) => ({ e, r: reaches(journey, e.gate) }));
  const allowed = scored.filter((s) => s.r.reachable === true).map((s) => s.e);
  const refused = scored.filter((s) => s.r.reachable === false).map((s) => s.e);
  const unverified = scored.filter((s) => s.r.reachable === null).map((s) => s.e);

  const kindWord = journey.type === "role" ? "an employee whose `staff.role` is" : "a signed-in";
  const notes = [];

  /* ROUTES THAT ADMIT THIS JOURNEY BY NAME, as opposed to routes anyone reaches.
     Without this split a journey that nothing admits still shows a healthy-looking
     "reaches 7 of 51", when the honest answer is that it reaches the login page
     and the health check and nothing else. */
  const generic = new Set(["open", "verified-other"]);
  const specific = allowed.filter((e) => !generic.has(e.gate.kind));

  const deadEnd = specific.length === 0 ? [
    "## FINDING — this journey reaches nothing",
    "",
    `**Not one endpoint in this system admits ${an(journey.subject)} \`${journey.subject}\`.**`,
    "",
    `${an(journey.subject) === "an" ? "An" : "A"} \`${journey.subject}\` is a real kind of account — they can be issued a session and sign in`,
    "(`src/auth/account-session.mjs`). Having signed in, every endpoint refuses them. The only",
    "routes they can reach are the ones anybody can reach without signing in at all: the login",
    "and health routes, and three that check a signature instead of a session.",
    "",
    "So the sign-in works and leads nowhere. `src/http/read-api.mjs` describes this exact",
    "failure in its own comments — *\"a client or partner could sign in and then read NOTHING,",
    "because every endpoint 401'd them\"* — and names it as what the `principals` option was",
    "added to fix. That fix was applied to some kinds and not to this one.",
    "",
    "**This is a finding for a human, not something to generate around.** Either endpoints are",
    "missing, or this account kind is not actually in use and should stop being offered.",
    ""
  ] : [];

  if (specific.length === 0) {
    notes.push(
      `**Nothing admits ${an(journey.subject)} \`${journey.subject}\` specifically** — see the finding above. Every route ` +
      `listed below is one anybody reaches without signing in.`
    );
  }

  const anyStaff = allowed.filter((e) => e.gate.anyStaff);
  if (anyStaff.length && journey.type === "role") {
    notes.push(
      `**${anyStaff.length} route${anyStaff.length === 1 ? " is" : "s are"} open to any signed-in employee, whatever their role.** ` +
      `That is not a gate on this journey specifically — anyone who can sign in reaches ${anyStaff.length === 1 ? "it" : "them"}: ` +
      anyStaff.map((e) => `\`/api/${e.key}\``).join(", ") + "."
    );
  }

  const secretFallback = allowed.filter((e) => e.gate.sharedSecretFallback);
  if (secretFallback.length) {
    notes.push(
      `**${secretFallback.length} route${secretFallback.length === 1 ? "" : "s"} also accept${secretFallback.length === 1 ? "s" : ""} a shared secret ` +
      `instead of a sign-in** (\`DASHBOARD_SECRET\`), so a caller holding that value reaches ${secretFallback.length === 1 ? "it" : "them"} ` +
      `without being anybody in particular: ` + secretFallback.map((e) => `\`/api/${e.key}\``).join(", ") + "."
    );
  }

  const openRoutes = allowed.filter((e) => e.gate.kind === "open");
  if (openRoutes.length) {
    notes.push(
      `**${openRoutes.length} route${openRoutes.length === 1 ? " is" : "s are"} genuinely open** — no sign-in needed, ` +
      `reachable by anyone and not by this journey in particular: ` +
      openRoutes.map((e) => `\`/api/${e.key}\``).join(", ") + ". These are the sign-in routes and the health check."
    );
  }

  /* Counted separately from "open" deliberately. These need no sign-in and are
     NOT open: a signed link, a provider signature, Inngest's own request signing.
     Listing them as open would be a false claim in the direction that causes
     harm — a reader would either panic or believe it. */
  const otherwiseVerified = allowed.filter((e) => e.gate.kind === "verified-other");
  if (otherwiseVerified.length) {
    notes.push(
      `**${otherwiseVerified.length} route${otherwiseVerified.length === 1 ? " needs" : "s need"} no sign-in but ` +
      `${otherwiseVerified.length === 1 ? "is" : "are"} NOT open.** ` +
      otherwiseVerified.map((e) => `\`/api/${e.key}\` (${e.gate.verifiedBy})`).join(", ") +
      ". Anyone can call these, but a caller without the right signature is refused."
    );
  }

  return [
    STAMP,
    "",
    `# ${journey.name} — actual`,
    "",
    `What the code **does** today for ${kindWord} \`${journey.subject}\`.`,
    "Generated from the routing table and the gate on each handler, not from a spec.",
    "",
    `> **Who this is, in the code:** ${journey.evidence}`,
    "",
    ...deadEnd,
    "## In one picture",
    "",
    diagram(journey, allowed, refused, unverified, specific.length),
    "",
    "## What they can reach",
    "",
    `**${allowed.length} of ${endpoints.length} routes.**`,
    "",
    table(allowed),
    "",
    ...(notes.length ? ["### Worth knowing", "", ...notes.map((n) => `- ${n}`), ""] : []),
    "## What they are blocked from",
    "",
    `**${refused.length} of ${endpoints.length} routes.**`,
    "",
    table(refused),
    "",
    ...(unverified.length
      ? ["## UNVERIFIED", "",
         "The gate on these could not be traced from the code, so this page does not claim",
         "either way whether this journey reaches them. Each one is a question for a human.",
         "", table(unverified), ""]
      : ["## UNVERIFIED", "", "_None — every route's gate was traced to its source._", ""]),
    "## How to check this yourself",
    "",
    "Every row above comes from two places, and you can open both:",
    "",
    "- **Which routes exist:** the `ROUTES` map in `netlify/functions/api.mjs`. A handler",
    "  missing from that map answers 404, so that map is the definition of what exists.",
    "- **Who each one lets in:** the gate written at the top of each `api/…` handler.",
    "",
    "Run `npm run journeys` to rebuild this file. `npm test` fails if it is out of date.",
    ""
  ].join("\n");
}

/* ---------------------------------------------------------------------------
   The index
   ------------------------------------------------------------------------ */

function readme(data) {
  const { journeys, endpoints, counts, roleSets, superRoleOnReadPath } = data;

  /* Journeys that can sign in and then reach nothing that names them. The most
     important thing on this page, so it is computed here rather than left for a
     reader to notice by comparing eight tables. */
  const generic = new Set(["open", "verified-other"]);
  const deadEnds = journeys.filter((j) => !j.missing &&
    endpoints.filter((e) => reaches(j, e.gate).reachable === true && !generic.has(e.gate.kind)).length === 0);

  const rows = journeys.map((j) => {
    if (j.missing) return `| [${j.name}](./${j.name}-actual.md) | — | **no such role exists** |`;
    const scored = endpoints.map((e) => reaches(j, e.gate));
    const can = scored.filter((s) => s.reachable === true).length;
    return `| [${j.name}](./${j.name}-actual.md) | \`${j.subject}\` | reaches ${can} of ${endpoints.length} routes |`;
  });

  return [
    STAMP,
    "",
    "# Journeys — what the system actually does",
    "",
    "One page per journey, showing who can reach what. **Generated from the code**, so it",
    "cannot drift into describing something that is not there.",
    "",
    "## Actual only — there are no `-intended` files here",
    "",
    "`CLAUDE.md` §4 describes a pair per journey: `-intended.md`, hand-written by a human, and",
    "`-actual.md`, generated from the code. **Only the actual files exist**, by the owner's",
    "decision. Agents do not author intended journeys, so an agent creating them would be",
    "writing the source of truth it is supposed to be checked against.",
    "",
    "That means one thing is missing on purpose: nothing here compares what the system does",
    "against what it was *meant* to do. These pages are a mirror, not a test.",
    "",
    "## The journeys",
    "",
    "| Journey | Who that is in the code | Reach |",
    "|---|---|---|",
    ...rows,
    "",
    "## What was found while generating these",
    "",
    `- **${counts.total} routes** are reachable in total.`,
    `- **${counts.unverified} route${counts.unverified === 1 ? " has a gate" : "s have gates"} that could not be traced.**` +
      (counts.unverified === 0 ? " Every gate resolved to its source." : " Each is marked UNVERIFIED on the pages that touch it."),
    `- **${counts.open} route${counts.open === 1 ? " is" : "s are"} genuinely open** (signing in, signing out, "who am I", and the health check).`,
    `- **${counts.verifiedOther} route${counts.verifiedOther === 1 ? " needs" : "s need"} no sign-in but ${counts.verifiedOther === 1 ? "is" : "are"} not open** — a signed link, a provider signature, and Inngest's own request signing. Anyone may call them; the wrong signature is refused.`,
    "- **`role-sales-manager` has nothing behind it.** `CLAUDE.md` §4 tracks the journey; no",
    "  such role exists in the code. See its page.",
    ...deadEnds.map((j) =>
      `- **Nothing admits ${an(j.subject)} \`${j.subject}\`.** They can sign in and then reach no endpoint at all. ` +
      `See [${j.name}](./${j.name}-actual.md).`),
    "",
    "## The role sets, spelled out",
    "",
    "Endpoints name a set like `ROLE_SETS.FINANCE`. Those names mean:",
    "",
    "| Set | Roles |",
    "|---|---|",
    ...Object.entries(roleSets).map(([k, v]) => `| \`${k}\` | ${v.join(", ")} |`),
    "",
    superRoleOnReadPath
      ? "> Note: the read path has a super-role, so some roles pass gates without being listed."
      : "> **There is no automatic super-role on the read path.** An owner reaches these routes\n" +
        "> only because `owner` is written into each set by hand. Remove it from one and the owner\n" +
        "> loses that route — nothing catches it. (`src/http/middleware/requireRole.mjs` has a\n" +
        "> separate curried gate that *does* carry `SUPER_ROLES`; `/api/inquiry` is the one route\n" +
        "> using it.)",
    "",
    "## Rebuilding",
    "",
    "```",
    "npm run journeys         # rewrite these files from the code",
    "npm run journeys:check   # fail if they are stale",
    "```",
    "",
    "`npm test` runs the check, so these cannot silently fall behind the code.",
    ""
  ].join("\n");
}

/** renderAll(data) → { "<filename>": "<contents>" } */
export function renderAll(data) {
  const files = {};
  for (const j of data.journeys) files[`${j.name}-actual.md`] = page(j, data);
  files["README.md"] = readme(data);
  return files;
}

export default { renderAll };
