#!/usr/bin/env node
/**
 * Write the testimonial slots on the sales page from
 * content/testimonials/testimonials.json.
 *
 *   node scripts/testimonials/build-slots.mjs           # rewrite the fragment
 *   node scripts/testimonials/build-slots.mjs --check    # fail if it is stale
 *
 * The page is a ClickFunnels custom-HTML fragment, not a component, so nothing
 * reads the JSON at runtime. This script is what keeps the two in step: the
 * JSON is the source of record and the markup is generated from it.
 *
 * Only records with status "approved" go on the page, ordered by sort_order.
 */
import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const repo = path.resolve(here, "../..");
const DATA = path.join(repo, "content/testimonials/testimonials.json");
const PAGE = path.join(repo, "clickfunnels-fragments/slo/slo-01-sales.html");

const START = "<!-- SLOT-TESTIMONIALS:";
const END = "<!-- /SLOT-TESTIMONIALS -->";

const esc = (s) =>
  String(s).replace(/[&<>]/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;" })[c]);

/** "Name, business type. Rest of it." -> bold lead + the rest. */
function splitCaption(caption) {
  const i = caption.indexOf(". ");
  if (i === -1) return { lead: caption, rest: "" };
  return { lead: caption.slice(0, i + 1), rest: caption.slice(i + 2) };
}

const records = JSON.parse(readFileSync(DATA, "utf8"))
  .filter((r) => r.status === "approved")
  .sort((a, b) => a.sort_order - b.sort_order);

if (!records.length) {
  console.error(
    "No approved testimonials. Nothing would show on the page — refusing to " +
      'empty the slot. Set status to "approved" in testimonials.json first.',
  );
  process.exit(1);
}

const cards = records
  .map((r) => {
    const { lead, rest } = splitCaption(r.caption);
    const poster = r.poster_src || r.video_src.replace(/\.mp4$/, "-poster.jpg");
    const who = esc(r.client_name);
    return `    <figure class="tcard">
      <div class="vslot">
        <video playsinline preload="metadata"
          poster="${esc(poster)}"
          src="${esc(r.video_src)}"
          title="${who}" aria-label="${who} testimonial"></video>
        <button class="tplay" type="button" aria-label="Play ${who}'s testimonial">
          <span class="tplay-pill">
            <svg viewBox="0 0 24 24" fill="currentColor" aria-hidden="true"><polygon points="6 4 20 12 6 20 6 4"/></svg>
            Play
          </span>
        </button>
      </div>
      <figcaption class="tcap"><b>${esc(lead)}</b> ${esc(rest)}</figcaption>
    </figure>`;
  })
  .join("\n");

const block = `${START} generated by scripts/testimonials/build-slots.mjs from
       content/testimonials/testimonials.json. Do not hand-edit — re-run the
       script. ${records.length} approved: ${records.map((r) => r.client_name).join(", ")}. -->
  <div class="proofgrid">
    <span class="kicker" style="text-align:center;grid-column:1/-1">From people who bought it</span>
${cards}
  </div>
  <script>
  (function(){
    // Click to play. No autoplay — the VSL at the top is the only video on this
    // page that starts by itself. Starting one stops the others so three
    // testimonials can never talk over each other.
    var cards=document.querySelectorAll('.fh-b .proofgrid .tcard');
    Array.prototype.forEach.call(cards,function(card){
      var v=card.querySelector('video'),o=card.querySelector('.tplay');
      if(!v||!o)return;
      function go(){
        Array.prototype.forEach.call(cards,function(other){
          if(other===card)return;
          var ov=other.querySelector('video');
          if(ov&&!ov.paused)ov.pause();
        });
        v.controls=true;
        var p=v.play();if(p&&p.catch)p.catch(function(){});
        o.classList.add('hidden');
      }
      o.addEventListener('click',go);
      v.addEventListener('click',function(){if(!o.classList.contains('hidden'))go();});
    });
  })();
  </script>
  ${END}`;

const page = readFileSync(PAGE, "utf8");
const a = page.indexOf(START);
if (a === -1) throw new Error(`could not find ${START} in ${PAGE}`);

let b = page.indexOf(END);
let tail;
if (b === -1) {
  // First run, before the end marker exists. Walk the divs and find the one
  // that actually closes .proofgrid. Taking the first </div> instead leaves the
  // old slots orphaned outside the grid, where they render at full size and
  // spill across the page — that shipped once, on 2026-09-27, and was caught
  // only by hit-testing the screenshot.
  const open = page.indexOf('<div class="proofgrid">', a);
  if (open === -1) throw new Error("could not find the proofgrid block");
  const tag = /<div\b|<\/div>/g;
  tag.lastIndex = open;
  let depth = 0;
  let close = -1;
  let m;
  while ((m = tag.exec(page))) {
    depth += m[0] === "</div>" ? -1 : 1;
    if (depth === 0) {
      close = m.index + m[0].length;
      break;
    }
  }
  if (close === -1) throw new Error("proofgrid block has unbalanced divs");
  tail = page.slice(close);
} else {
  tail = page.slice(b + END.length);
}

const next = page.slice(0, a) + block + tail;

if (process.argv.includes("--check")) {
  if (next !== page) {
    console.error(
      "slo-01-sales.html testimonial slots are stale — run " +
        "node scripts/testimonials/build-slots.mjs",
    );
    process.exit(1);
  }
  console.log("testimonial slots are in step with testimonials.json");
  process.exit(0);
}

writeFileSync(PAGE, next);
console.log(
  `wrote ${records.length} slot(s) into ${path.relative(repo, PAGE)}: ` +
    records.map((r) => r.client_name).join(", "),
);
