// Mermaid renderers for docs/diagrams. Pure string builders — every input comes
// from extract.mjs, nothing is read or written here.
//
// GitHub renders ```mermaid fences natively, so the output is plain Markdown with
// no build step and no images to keep in sync.

export const BANNER = "<!-- GENERATED by scripts/diagrams/generate.mjs — do not edit by hand. Run `npm run diagrams`. -->";

// Mermaid node ids must be bare identifiers; labels carry the real text.
const id = (s) => String(s).replace(/[^A-Za-z0-9_]/g, "_");
const q = (s) => `"${String(s).replace(/"/g, "'")}"`;

const header = (title, sources, blurb) => [
  BANNER,
  "",
  `# ${title}`,
  "",
  blurb,
  "",
  `**Generated from:** ${sources.map((s) => `\`${s}\``).join(", ")}`,
  ""
].join("\n");

// --- 1. Event flow ----------------------------------------------------------

export function renderEventFlow({ canonicalGroups, adapters, busHandlers, workflows }) {
  const spine = canonicalGroups.find((g) => /spine/i.test(g.title))?.events || [];
  const handlersByEvent = new Map();
  for (const h of busHandlers) {
    if (!handlersByEvent.has(h.event)) handlersByEvent.set(h.event, []);
    handlersByEvent.get(h.event).push(h);
  }
  const workflowCount = new Map();
  for (const w of workflows) for (const e of w.events) workflowCount.set(e, (workflowCount.get(e) || 0) + 1);

  const out = [
    header(
      "Event flow",
      ["src/events/canonical.mjs", "src/events/bus.mjs", "src/adapters/", "src/handlers/", "src/workflows/"],
      "How a fact gets into the platform and what reacts to it. Every inbound signal becomes a canonical\n" +
      "event on the bus first; nothing reacts to a webhook directly."
    ),
    "## Ingress path",
    "",
    "```mermaid",
    "flowchart LR",
    "  subgraph EXT[External systems]",
    "    direction TB"
  ];

  for (const a of adapters) out.push(`    ext_${id(a.name)}[${q(a.title || a.name)}]`);
  out.push("  end", "  subgraph ADP[Adapters — verify, normalize, emit]", "    direction TB");
  for (const a of adapters) {
    const label = a.inbound ? `${a.name}<br/>${a.scheme || "signed"}` : `${a.name}<br/>direct call`;
    out.push(`    adp_${id(a.name)}[${q(label)}]`);
  }
  out.push("  end");
  out.push("  BUS[(events table<br/>append-only, idempotent)]");
  out.push("  REG[[registry handlers<br/>synchronous]]");
  out.push("  ING[[Inngest functions<br/>durable, with waits]]");
  out.push("");
  for (const a of adapters) out.push(`  ext_${id(a.name)} --> adp_${id(a.name)}`);
  for (const a of adapters) {
    const evs = a.events.length ? a.events.join("<br/>") : "—";
    out.push(`  adp_${id(a.name)} -- ${q(evs)} --> BUS`);
  }
  out.push("  BUS --> REG", "  BUS --> ING", "```", "");

  out.push(
    "## Journey spine",
    "",
    "The ordered backbone of a client's life in the system. Side events and billing events hang off it",
    "but do not advance it.",
    "",
    "```mermaid",
    "flowchart LR"
  );
  spine.forEach((e, i) => {
    out.push(`  s${i}[${q(e)}]`);
    if (i > 0) out.push(`  s${i - 1} --> s${i}`);
  });
  out.push("```", "");

  out.push("## Reactions per event", "");
  out.push("| event | group | bus handlers | Inngest functions |");
  out.push("|---|---|---|---|");
  for (const g of canonicalGroups) {
    for (const e of g.events) {
      const hs = handlersByEvent.get(e) || [];
      out.push(`| \`${e}\` | ${g.title} | ${hs.length ? hs.map((h) => `\`${h.fn}\``).join(", ") : "—"} | ${workflowCount.get(e) || 0} |`);
    }
  }
  out.push("");
  out.push("An event with no handler and no function is declared but inert — it can be emitted and stored,");
  out.push("and nothing happens. That is a real state in this repo, not an omission in the diagram.");
  out.push("");
  return out.join("\n");
}

// --- 2. Rails (one state machine per pipeline) ------------------------------

export function renderRail(pipeline, stageMoves) {
  const moves = stageMoves.filter((m) => m.pipeline === pipeline.key);
  const movesByStage = new Map();
  for (const m of moves) {
    if (!movesByStage.has(m.stage)) movesByStage.set(m.stage, []);
    movesByStage.get(m.stage).push(m.workflow);
  }

  const out = [
    header(
      `Rail: ${pipeline.name}`,
      ["db/seed/002_pipelines.sql", "src/workflows/"],
      `Pipeline key \`${pipeline.key}\` — ${pipeline.stages.length} stages.`
    ),
    "```mermaid",
    "stateDiagram-v2"
  ];

  for (const s of pipeline.stages) out.push(`    state ${q(s.name)} as ${id(s.key)}`);
  out.push("");
  if (pipeline.stages.length) {
    out.push(`    [*] --> ${id(pipeline.stages[0].key)}`);
    for (let i = 1; i < pipeline.stages.length; i++) {
      out.push(`    ${id(pipeline.stages[i - 1].key)} --> ${id(pipeline.stages[i].key)}`);
    }
    out.push(`    ${id(pipeline.stages.at(-1).key)} --> [*]`);
  }
  for (const [stage, wfs] of movesByStage) {
    out.push(`    note right of ${id(stage)} : moved by ${wfs.join(", ")}`);
  }
  out.push("```", "");

  out.push(
    "**Read the arrows as seeded display order, not as permitted transitions.**",
    "`002_pipelines.sql` defines each stage's `sort_order`; it does not define a transition table, and",
    "this diagram does not invent one.",
    "",
    "The notes are the part that *is* code-backed: they mark the stages some workflow actually moves a",
    "card into, via `moveCardToStage`.",
    ""
  );

  out.push("| # | stage key | name | moved into by |");
  out.push("|---|---|---|---|");
  for (const s of pipeline.stages) {
    const wfs = movesByStage.get(s.key);
    out.push(`| ${s.sort} | \`${s.key}\` | ${s.name} | ${wfs ? wfs.map((w) => `\`${w}\``).join(", ") : "—"} |`);
  }
  out.push("");

  if (moves.length === 0) {
    out.push(
      "> **Nothing in this repo moves a card on this rail.** Every stage above is seeded and reachable only",
      "> by a write from outside these workflows. For Alt-Fin that is the documented rule (Spec §5: those",
      "> cards move ONLY from Lendflow webhooks). For the others it means the rail is seeded ahead of the",
      "> workflows that will drive it.",
      ""
    );
  }
  return out.join("\n");
}

export function renderRailsIndex(pipelines, stageMoves) {
  const out = [
    header(
      "Rails",
      ["db/seed/002_pipelines.sql", "src/workflows/"],
      "The 7 pipelines seeded by `002_pipelines.sql`, one state machine each."
    ),
    "| rail | key | stages | code-driven moves |",
    "|---|---|---|---|"
  ];
  for (const p of pipelines) {
    const n = stageMoves.filter((m) => m.pipeline === p.key).length;
    out.push(`| [${p.name}](./${p.key}.md) | \`${p.key}\` | ${p.stages.length} | ${n || "—"} |`);
  }
  out.push("");
  return out.join("\n");
}

// --- 3. Adapter boundary ----------------------------------------------------

export function renderAdapterBoundary({ adapters }) {
  const out = [
    header(
      "Adapter boundary",
      ["src/adapters/", "src/events/canonical.mjs"],
      "Where the platform stops trusting the outside world. An adapter verifies, normalizes and emits —\n" +
      "and does nothing else. All business reaction happens on the far side of the bus."
    ),
    "```mermaid",
    "flowchart TB",
    "  subgraph OUTSIDE[Outside the trust boundary]",
    "    direction LR"
  ];
  for (const a of adapters) out.push(`    o_${id(a.name)}[${q(a.title || a.name)}]`);
  out.push("  end", "  subgraph BOUNDARY[Adapter layer]", "    direction LR");
  for (const a of adapters) {
    const gate = a.inbound ? `${a.scheme || "signature"}<br/>fail-closed` : "no signature<br/>direct call";
    out.push(`    b_${id(a.name)}[${q(`${a.name}<br/>${gate}`)}]`);
  }
  out.push("  end", "  BUS[(canonical event bus)]", "");
  /* An adapter reaches the bus only if it actually emits something. The arrow
     used to be unconditional, which drew twilio-status.mjs — a delivery-receipt
     handler that emits nothing and updates a message row instead — as a feeder
     of the canonical event bus. A reader checking "what puts events on the bus"
     would have counted a source that never does. */
  for (const a of adapters) {
    out.push(`  o_${id(a.name)} --> b_${id(a.name)}`);
    if (a.events.length) out.push(`  b_${id(a.name)} --> BUS`);
    else out.push(`  b_${id(a.name)} --> DB_${id(a.name)}[("messages<br/>status update")]`);
  }
  out.push("```", "");

  out.push("| adapter | direction | auth | emits | verified against a real payload? |");
  out.push("|---|---|---|---|---|");
  for (const a of adapters) {
    const dir = [a.inbound ? "inbound webhook" : null, a.outbound ? "outbound call" : null].filter(Boolean).join(" + ") || "direct call";
    const auth = a.verifiers.length ? `\`${a.verifiers.join("`, `")}\` (${a.scheme})` : "none — not a webhook";
    const evs = a.events.length ? a.events.map((e) => `\`${e}\``).join("<br/>") : "—";
    out.push(`| \`${a.name}\` | ${dir} | ${auth} | ${evs} | ${a.unverified ? "⚠️ **no** — carries a CONFIRM banner" : "yes"} |`);
  }
  out.push("");
  const unverified = adapters.filter((a) => a.unverified);
  if (unverified.length) {
    out.push(
      `> ⚠️ ${unverified.length} of ${adapters.length} adapters still carry a \`CONFIRM\` banner in their header:`,
      `> ${unverified.map((a) => `\`${a.name}\``).join(", ")}. Their field paths, header names or signature`,
      "> schemes were written from documentation rather than from an observed payload. The boundary is drawn",
      "> here as the code intends it, which is not the same as how the vendor actually behaves.",
      ""
    );
  }
  return out.join("\n");
}

// --- 4. Agent trigger map ---------------------------------------------------

export function renderAgentTriggers({ workflows, canonicalGroups }) {
  const byEvent = new Map();
  for (const w of workflows) {
    for (const e of w.events) {
      if (!byEvent.has(e)) byEvent.set(e, []);
      byEvent.get(e).push(w);
    }
  }
  const triggering = [...byEvent.keys()].sort();

  const out = [
    header(
      "Agent trigger map",
      ["src/workflows/index.mjs", "src/events/canonical.mjs"],
      "Which canonical event wakes which automation. \"Agent\" here means a registered Inngest function —\n" +
      "the " + workflows.length + " workflow ports in `src/workflows/`, read off their real `createFunction` triggers.\n" +
      "(The AG-xx prompt-driven agents in `wireframes/agent-editor.html` are a UI mock with no code behind\n" +
      "them yet, and are deliberately not drawn here.)"
    ),
    "```mermaid",
    "flowchart LR"
  ];
  for (const e of triggering) {
    out.push(`  e_${id(e)}([${q(e)}])`);
    for (const w of byEvent.get(e)) out.push(`  e_${id(e)} --> w_${id(w.id)}[${q(w.id)}]`);
  }
  out.push("```", "");

  out.push("## Fan-out per event", "");
  out.push("| event | functions | triggered |");
  out.push("|---|---|---|");
  for (const e of triggering) {
    const ws = byEvent.get(e);
    out.push(`| \`${e}\` | ${ws.length} | ${ws.map((w) => `\`${w.id}\``).join(", ")} |`);
  }
  out.push("");

  const allEvents = canonicalGroups.flatMap((g) => g.events);
  const inert = allEvents.filter((e) => !byEvent.has(e));
  if (inert.length) {
    out.push(
      "## Canonical events that trigger nothing",
      "",
      "Declared in `canonical.mjs`, emitted or emittable, with no Inngest function listening:",
      "",
      ...inert.map((e) => `- \`${e}\``),
      "",
      "Some are handled synchronously by a bus handler instead (see [event-flow](./event-flow.md)); the",
      "commission and billing events are proposed-but-unbuilt. Either way, nothing durable reacts to them.",
      ""
    );
  }

  const multi = workflows.filter((w) => w.events.length > 1);
  if (multi.length) {
    out.push("## Functions with more than one trigger", "");
    out.push("| function | events |");
    out.push("|---|---|");
    for (const w of multi) out.push(`| \`${w.id}\` | ${w.events.map((e) => `\`${e}\``).join(", ")} |`);
    out.push("");
  }
  return out.join("\n");
}

// --- index ------------------------------------------------------------------

export function renderIndex(data) {
  return [
    BANNER,
    "",
    "# Diagrams",
    "",
    "Generated from the code, not from any spec document. Mermaid renders natively on GitHub, so these",
    "are plain Markdown — no build step, no exported images to fall out of date.",
    "",
    "| diagram | what it answers |",
    "|---|---|",
    "| [Event flow](./event-flow.md) | How does a fact get in, and what reacts to it? |",
    "| [Rails](./rails/README.md) | What are the 7 pipelines and what moves a card along them? |",
    "| [Adapter boundary](./adapter-boundary.md) | Where does the platform stop trusting the outside world? |",
    "| [Agent trigger map](./agent-triggers.md) | Which event wakes which automation? |",
    "",
    "## Regenerating",
    "",
    "```sh",
    "npm run diagrams        # rewrite docs/diagrams/ from the current code",
    "npm run diagrams:check  # fail if the committed diagrams are stale",
    "```",
    "",
    "`diagrams:check` is also asserted by the test suite (`scripts/diagrams/generate.test.mjs`), so a",
    "change to an event name, a workflow trigger, a pipeline stage or an adapter fails `npm test` until",
    "the diagrams are regenerated. That is the whole point: they cannot drift quietly.",
    "",
    "## Sources",
    "",
    "| source | supplies |",
    "|---|---|",
    "| `src/events/canonical.mjs` | the " + data.canonicalEvents.length + " canonical event names and their grouping |",
    "| `src/workflows/index.mjs` | " + data.workflows.length + " registered Inngest functions and their triggers |",
    "| `db/seed/002_pipelines.sql` | " + data.pipelines.length + " rails and their stages |",
    "| `src/adapters/*.mjs` | " + data.adapters.length + " adapters, their auth scheme and emitted events |",
    "| `src/handlers/*.mjs` | " + data.busHandlers.length + " synchronous bus handler registrations |",
    "",
    "Facts available as JS values are **imported** rather than text-matched, so a rename surfaces as a",
    "changed diagram instead of a silently empty section.",
    ""
  ].join("\n");
}

/** Every file the generator writes: path (relative to docs/diagrams) -> contents. */
export function renderAll(data) {
  const files = {
    "README.md": renderIndex(data),
    "event-flow.md": renderEventFlow(data),
    "adapter-boundary.md": renderAdapterBoundary(data),
    "agent-triggers.md": renderAgentTriggers(data),
    "rails/README.md": renderRailsIndex(data.pipelines, data.stageMoves)
  };
  for (const p of data.pipelines) files[`rails/${p.key}.md`] = renderRail(p, data.stageMoves);
  return files;
}
