-- ===========================================================================
-- fix-owner-login.sql — restore the owner login for chris@fundhub.ai
-- ===========================================================================
--
-- WHAT THIS DOES
--   Makes chris@fundhub.ai a working, active OWNER login with the password:
--
--       j32edOAlODrrRfT4H3GZ
--
--   It ensures the default org exists, then UPDATEs the staff row if one is
--   already there or INSERTs it if it is not, sets status/role/active to the
--   exact values the login path requires, clears the failed-attempt rate
--   limiter, and finishes with a SELECT so you can see the result.
--
-- WHERE TO RUN IT
--   Supabase Dashboard -> SQL Editor -> New query -> paste -> Run.
--   No CLI, no credentials, no connection string needed.
--
-- IT IS SAFE TO RUN TWICE
--   Every statement is idempotent. The org insert is guarded by NOT EXISTS,
--   the staff write is UPDATE-then-INSERT-WHERE-NOT-EXISTS, and re-running
--   simply rewrites the same values. There is no blind INSERT anywhere.
--
-- ABOUT THE HASH
--   The password_hash below is NOT bcrypt. This codebase uses scrypt (RFC 7914)
--   via node:crypto, stored as a PHC-style string:
--       $scrypt$N=32768,r=8,p=1$<salt-base64url>$<derivedkey-base64url>
--   It was generated by this repo's own src/auth/hash.mjs hashPassword() and
--   round-trip verified with that same module's verifyPassword() -> true.
--   verifyPassword() reads N, r, p and the key length back out of the string
--   itself, and the salt is embedded, so there is no pepper, no secret key and
--   no environment dependency. Pasting it here works.
--
--   Do NOT wrap the hash in PostgreSQL dollar-quoting ($$...$$) — it contains
--   '$scrypt$', which would terminate the quote. Single quotes are correct and
--   the string contains no quote or backslash to escape.
--   Do NOT let it wrap onto two lines or pick up a trailing space: the verify
--   fails SILENTLY on a malformed hash and looks exactly like a wrong password.
--   Expected length is 90 characters — the final SELECT checks this for you.
--
-- ABOUT THE ORG SLUG ('fundhub')
--   Login resolves the org with: SELECT id FROM orgs WHERE slug = $1
--   where $1 = process.env.DEFAULT_ORG_SLUG || 'fundhub'  (src/auth/org.mjs:5,12).
--   It does NOT use orgs.is_default. If the DEFAULT_ORG_SLUG env var in Netlify
--   is set to something other than 'fundhub', find-and-replace 'fundhub' in
--   THIS ENTIRE FILE before running it. DEPLOY.md documents it as 'fundhub'
--   and db/schema/001_init.sql seeds exactly that slug, so the default is
--   almost certainly correct.
--
-- AFTER RUNNING THIS
--   The login form pre-fills the old demo password. On the login page open the
--   browser console and run  localStorage.clear()  then reload, or you may be
--   answered by the client-side demo mode instead of the real backend.
--   See scripts/fix-owner-login.md for the full four-step runbook.
-- ===========================================================================


-- ---------------------------------------------------------------------------
-- 1. Ensure the default org exists, found the same way login finds it.
-- ---------------------------------------------------------------------------
INSERT INTO orgs (slug, name, is_default)
SELECT 'fundhub', 'Fundhub', true
WHERE NOT EXISTS (SELECT 1 FROM orgs WHERE slug = 'fundhub');


-- ---------------------------------------------------------------------------
-- 2. If the staff row already exists, repair it in place.
--    Note: name is preserved if it is already set, because staff.name is
--    NOT NULL and we should not clobber a real name with a placeholder.
-- ---------------------------------------------------------------------------
UPDATE staff s
   SET password_hash = '$scrypt$N=32768,r=8,p=1$OGlsg95nW_gkPZiUiS7krg$XwNlQqtGLvU8GX1_A8l7JPubLi1o4vmjM_1ZPq9DfWU',
       status        = 'active',
       role          = 'owner',
       email         = 'chris@fundhub.ai',
       name          = COALESCE(NULLIF(btrim(s.name), ''), 'Chris Stanbridge')
  FROM orgs o
 WHERE o.slug = 'fundhub'
   AND s.org_id = o.id
   AND lower(s.email) = 'chris@fundhub.ai';


-- ---------------------------------------------------------------------------
-- 3. If it does not exist, create it.
--    org_id and name are NOT NULL with no default, so both are supplied.
--    id, comp, created_at, updated_at all have defaults and are omitted.
--    employee_code is assigned by the trg_staff_employee_code BEFORE INSERT
--    trigger, so it is omitted too.
--
--    A WHERE NOT EXISTS guard is used rather than ON CONFLICT because the
--    unique index is PARTIAL and on an EXPRESSION —
--      CREATE UNIQUE INDEX idx_staff_email_org
--        ON staff (org_id, lower(email)) WHERE email IS NOT NULL
--    — which a plain ON CONFLICT (org_id, email) cannot infer, and would
--    error rather than upsert.
-- ---------------------------------------------------------------------------
INSERT INTO staff (org_id, email, name, role, status, password_hash)
SELECT o.id,
       'chris@fundhub.ai',
       'Chris Stanbridge',
       'owner',
       'active',
       '$scrypt$N=32768,r=8,p=1$OGlsg95nW_gkPZiUiS7krg$XwNlQqtGLvU8GX1_A8l7JPubLi1o4vmjM_1ZPq9DfWU'
  FROM orgs o
 WHERE o.slug = 'fundhub'
   AND NOT EXISTS (
         SELECT 1 FROM staff s
          WHERE s.org_id = o.id
            AND lower(s.email) = 'chris@fundhub.ai'
       );


-- ---------------------------------------------------------------------------
-- 4. staff.active is a SECOND, separate kill switch, added by
--    db/migrations/012_attribution.sql. It is not part of the status CHECK
--    constraint and is easy to miss: if it is false, a CORRECT password still
--    returns 403. The login path reads it defensively as
--    (to_jsonb(s) ->> 'active'), which works whether or not that migration
--    landed — so this block is guarded the same way and is a no-op if the
--    column does not exist.
-- ---------------------------------------------------------------------------
DO $fix$
BEGIN
  IF EXISTS (
        SELECT 1 FROM information_schema.columns
         WHERE table_schema = 'public'
           AND table_name   = 'staff'
           AND column_name  = 'active'
     ) THEN
    EXECUTE $q$
      UPDATE staff s
         SET active = true
        FROM orgs o
       WHERE o.slug = 'fundhub'
         AND s.org_id = o.id
         AND lower(s.email) = 'chris@fundhub.ai'
    $q$;
  END IF;
END
$fix$;


-- ---------------------------------------------------------------------------
-- 5. Clear the failed-attempt rate limiter for this email.
--    Limits are 5 failures per email / 20 per IP in a rolling 15 minutes
--    (src/auth/login.mjs). A successful login clears the counter on its own,
--    and the window expires by itself, but clearing it now removes any chance
--    of a 429 masking the fix on the very next attempt.
-- ---------------------------------------------------------------------------
DELETE FROM auth_attempts
 WHERE lower(email) = 'chris@fundhub.ai'
   AND NOT successful;


-- ---------------------------------------------------------------------------
-- 6. Confirmation. Expect EXACTLY ONE row, reading:
--       email        chris@fundhub.ai
--       role         owner
--       status       active
--       active       true
--       org_slug     fundhub
--       hash_len     90
--       hash_clean   true
--       hash_algo    $scrypt$N=32768,r=8,p=1
--    If hash_len is not 90 or hash_clean is false, the paste was mangled —
--    re-run this file. If you get ZERO rows, the org slug is wrong: check the
--    DEFAULT_ORG_SLUG env var in Netlify and see the header note above.
-- ---------------------------------------------------------------------------
SELECT s.id,
       s.email,
       s.role,
       s.status,
       s.org_id,
       o.slug                                    AS org_slug,
       length(s.password_hash)                   AS hash_len,
       (s.password_hash = btrim(s.password_hash)) AS hash_clean,
       split_part(s.password_hash, '$', 2) || '$' ||
       split_part(s.password_hash, '$', 3)       AS hash_algo
  FROM staff s
  JOIN orgs o ON o.id = s.org_id
 WHERE lower(s.email) = 'chris@fundhub.ai'
 ORDER BY (o.slug = 'fundhub') DESC;
