-- ===========================================================================
-- fix-owner-login.sql — restore the owner login for chris@fundhub.ai
-- ===========================================================================
--
-- WHAT THIS DOES
--   Makes chris@fundhub.ai a working, active OWNER login with the password:
--
--       j32edOAlODrrRfT4H3GZ
--
--   It UPDATEs the staff row if one is already there or INSERTs it if it is
--   not, sets status/role/active to the exact values the login path requires,
--   clears the failed-attempt rate limiter, and finishes with a single SELECT
--   whose VERDICT column tells you plainly whether login will now work.
--
-- WHERE TO RUN IT
--   Supabase Dashboard -> SQL Editor -> New query -> paste -> Run.
--   No CLI, no credentials, no connection string needed.
--
-- IT IS SAFE TO RUN TWICE
--   Every statement is idempotent. The staff write is
--   UPDATE-then-INSERT-WHERE-NOT-EXISTS, and re-running simply rewrites the
--   same values. There is no blind INSERT anywhere.
--
-- ---------------------------------------------------------------------------
-- THE ONE THING YOU MIGHT HAVE TO EDIT: THE ORG SLUG
-- ---------------------------------------------------------------------------
--   Login resolves the org with:  SELECT id FROM orgs WHERE slug = $1
--   where $1 = process.env.DEFAULT_ORG_SLUG || 'fundhub'  (src/auth/org.mjs:5,12).
--   It does NOT use orgs.is_default.
--
--   This file therefore hardcodes the slug 'fundhub' in several places. If the
--   DEFAULT_ORG_SLUG env var in Netlify is set to anything else, find-and-
--   replace it throughout THIS ENTIRE FILE before running it — but replace the
--   QUOTED 9-CHARACTER STRING  'fundhub'  (single quotes included), NOT the
--   bare word. The bare word also appears inside the email 'chris@fundhub.ai',
--   and rewriting that would create an account under an address nobody is
--   trying to log in as, while still printing "LOGIN WILL WORK". Step 0 has a
--   tripwire for exactly that mistake and will refuse to run.
--
--   You do not have to guess. Step 0 below REFUSES TO RUN and prints every
--   slug that actually exists in your database if 'fundhub' is not one of
--   them. It deliberately does NOT create the org for you: creating it would
--   produce a second, empty org, put the new staff row in THAT org, print a
--   perfect-looking confirmation, and still leave login returning
--   "Wrong email or password." — which is the exact dead end this file exists
--   to avoid.
--
-- ABOUT THE HASH
--   The password_hash below is NOT bcrypt. This codebase uses scrypt (RFC 7914)
--   via node:crypto, stored as a PHC-style string:
--       $scrypt$N=32768,r=8,p=1$<salt-base64url>$<derivedkey-base64url>
--   It was generated by this repo's own src/auth/hash.mjs hashPassword() and
--   round-trip verified with that same module's verifyPassword() -> true.
--   verifyPassword() reads N, r, p and the key length back out of the string
--   itself, and the salt is embedded, so there is no pepper, no secret key and
--   no environment dependency. Pasting it here works.
--
--   Do NOT wrap the hash in PostgreSQL dollar-quoting ($$...$$) — it contains
--   '$scrypt$', which would terminate the quote. Single quotes are correct and
--   the string contains no quote or backslash to escape.
--   Do NOT let it wrap onto two lines or pick up a trailing space: the verify
--   fails SILENTLY on a malformed hash and looks exactly like a wrong password.
--   Expected length is 90 characters — the final SELECT checks this for you.
--
-- AFTER RUNNING THIS
--   Clear localStorage on the login page (F12 -> localStorage.clear() ->
--   reload) before signing in, or you may be answered by the client-side demo
--   mode instead of the real backend.
--   See scripts/fix-owner-login.md for the full runbook.
-- ===========================================================================


-- ---------------------------------------------------------------------------
-- 0. GUARD. Abort loudly if the org this file targets does not exist, and say
--    what does exist. Runs FIRST so nothing has been written when it fires.
--
--    The one exception: a completely empty orgs table means the database has
--    never been migrated at all (db/schema/001_init.sql seeds 'fundhub'), so
--    there is no other org to be confused with and creating it is unambiguous.
-- ---------------------------------------------------------------------------
DO $fix$
DECLARE
  v_slug   text := 'fundhub';            -- keep in sync with the rest of this file
  v_email  text := 'chris@fundhub.ai';   -- must NOT be edited
  v_count  int;
  v_slugs  text;
BEGIN
  -- Tripwire for a botched find-and-replace. If the bare word was replaced
  -- instead of the quoted slug literal, the EMAIL was rewritten too and this
  -- script would cheerfully build an account under an address nobody is
  -- signing in with. The expected value below is assembled from fragments on
  -- purpose, so that the same careless replace cannot rewrite the check as well.
  IF v_email <> 'chris' || '@' || 'fund' || 'hub' || '.ai' THEN
    RAISE EXCEPTION
      'STOPPED — the email literal in this file has been altered to %. You replaced the bare word instead of the quoted slug. Re-copy the file and replace only the 9-character string with its single quotes. NOTHING WAS CHANGED.',
      quote_literal(v_email);
  END IF;

  SELECT count(*) INTO v_count FROM orgs;

  IF v_count = 0 THEN
    INSERT INTO orgs (slug, name, is_default) VALUES (v_slug, 'Fundhub', true);
    RAISE NOTICE 'orgs was empty — created org %', v_slug;
    RETURN;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM orgs WHERE slug = v_slug) THEN
    SELECT string_agg(quote_literal(slug), ', ' ORDER BY slug) INTO v_slugs FROM orgs;
    RAISE EXCEPTION
      'STOPPED — no org has slug %. Your database contains: %. Find-and-replace that slug throughout this file (it must equal the DEFAULT_ORG_SLUG env var in Netlify) and run it again. NOTHING WAS CHANGED.',
      quote_literal(v_slug), v_slugs;
  END IF;
END
$fix$;


-- ---------------------------------------------------------------------------
-- 1. If the staff row already exists, repair it in place.
--    Note: name is preserved if it is already set, because staff.name is
--    NOT NULL and we should not clobber a real name with a placeholder.
-- ---------------------------------------------------------------------------
UPDATE staff s
   SET password_hash = '$scrypt$N=32768,r=8,p=1$OGlsg95nW_gkPZiUiS7krg$XwNlQqtGLvU8GX1_A8l7JPubLi1o4vmjM_1ZPq9DfWU',
       status        = 'active',
       role          = 'owner',
       email         = 'chris@fundhub.ai',
       name          = COALESCE(NULLIF(btrim(s.name), ''), 'Chris Stanbridge')
  FROM orgs o
 WHERE o.slug = 'fundhub'
   AND s.org_id = o.id
   AND lower(s.email) = 'chris@fundhub.ai';


-- ---------------------------------------------------------------------------
-- 2. If it does not exist, create it.
--    org_id and name are NOT NULL with no default, so both are supplied.
--    id, comp, created_at, updated_at all have defaults and are omitted.
--    employee_code is assigned by the trg_staff_employee_code BEFORE INSERT
--    trigger, so it is omitted too.
--
--    A WHERE NOT EXISTS guard is used rather than ON CONFLICT because the
--    unique index is PARTIAL and on an EXPRESSION —
--      CREATE UNIQUE INDEX idx_staff_email_org
--        ON staff (org_id, lower(email)) WHERE email IS NOT NULL
--    — which a plain ON CONFLICT (org_id, email) cannot infer, and would
--    error rather than upsert.
-- ---------------------------------------------------------------------------
INSERT INTO staff (org_id, email, name, role, status, password_hash)
SELECT o.id,
       'chris@fundhub.ai',
       'Chris Stanbridge',
       'owner',
       'active',
       '$scrypt$N=32768,r=8,p=1$OGlsg95nW_gkPZiUiS7krg$XwNlQqtGLvU8GX1_A8l7JPubLi1o4vmjM_1ZPq9DfWU'
  FROM orgs o
 WHERE o.slug = 'fundhub'
   AND NOT EXISTS (
         SELECT 1 FROM staff s
          WHERE s.org_id = o.id
            AND lower(s.email) = 'chris@fundhub.ai'
       );


-- ---------------------------------------------------------------------------
-- 3. staff.active is a SECOND, separate kill switch, added by
--    db/migrations/012_attribution.sql. It is not part of the status CHECK
--    constraint and is easy to miss: if it is false, a CORRECT password still
--    returns 403. The login path reads it defensively as
--    (to_jsonb(s) ->> 'active'), which works whether or not that migration
--    landed — so this block is guarded the same way and is a no-op if the
--    column does not exist.
-- ---------------------------------------------------------------------------
DO $fix$
BEGIN
  IF EXISTS (
        SELECT 1 FROM information_schema.columns
         WHERE table_schema = 'public'
           AND table_name   = 'staff'
           AND column_name  = 'active'
     ) THEN
    EXECUTE $q$
      UPDATE staff s
         SET active = true
        FROM orgs o
       WHERE o.slug = 'fundhub'
         AND s.org_id = o.id
         AND lower(s.email) = 'chris@fundhub.ai'
    $q$;
  END IF;
END
$fix$;


-- ---------------------------------------------------------------------------
-- 4. Clear the failed-attempt rate limiter for this email.
--    Limits are 5 failures per email / 20 per IP in a rolling 15 minutes
--    (src/auth/login.mjs). A successful login clears the counter on its own,
--    and the window expires by itself, but clearing it now removes any chance
--    of a 429 masking the fix on the very next attempt.
--
--    Guarded with to_regclass so a database that somehow lacks auth_attempts
--    cannot abort the whole script and roll back the repair above.
-- ---------------------------------------------------------------------------
DO $fix$
BEGIN
  IF to_regclass('public.auth_attempts') IS NOT NULL THEN
    EXECUTE $q$
      DELETE FROM auth_attempts
       WHERE lower(email) = 'chris@fundhub.ai'
         AND NOT successful
    $q$;
  END IF;
END
$fix$;


-- ---------------------------------------------------------------------------
-- 5. Confirmation. READ THE `verdict` COLUMN — it is the whole answer.
--
--    Expect ONE row reading:
--       verdict     LOGIN WILL WORK
--       email       chris@fundhub.ai
--       role        owner
--       status      active
--       active      true
--       org_slug    fundhub
--       hash_len    90
--       hash_clean  t
--       hash_algo   $scrypt$N=32768,r=8,p=1
--
--    Anything else and `verdict` names the specific problem. If you get MORE
--    than one row, a staff row for this email also exists in another org —
--    only the row whose org_slug matches the slug at the top of this file can
--    log in; the others are labelled IGNORED and are harmless.
--
--    `auth_tables_present` matters too: the login path also needs `sessions`
--    and `auth_attempts`. If either is missing, a CORRECT password still
--    returns HTTP 500 — a schema problem, not a password problem.
-- ---------------------------------------------------------------------------
SELECT CASE
         WHEN o.slug <> 'fundhub'
           THEN 'IGNORED — this row is in org "' || o.slug || '", not the login org'
         WHEN s.password_hash IS DISTINCT FROM
              '$scrypt$N=32768,r=8,p=1$OGlsg95nW_gkPZiUiS7krg$XwNlQqtGLvU8GX1_A8l7JPubLi1o4vmjM_1ZPq9DfWU'
           THEN 'BROKEN — password_hash is not the expected value; re-run this file'
         WHEN s.status <> 'active'
           THEN 'BROKEN — status is "' || s.status || '", must be "active"'
         WHEN COALESCE(to_jsonb(s) ->> 'active', 'true') = 'false'
           THEN 'BROKEN — staff.active is false'
         WHEN to_regclass('public.sessions') IS NULL
           THEN 'BROKEN — the sessions table is missing; login will 500'
         WHEN to_regclass('public.auth_attempts') IS NULL
           THEN 'BROKEN — the auth_attempts table is missing; login will 500'
         ELSE 'LOGIN WILL WORK'
       END                                         AS verdict,
       s.email,
       s.role,
       s.status,
       COALESCE(to_jsonb(s) ->> 'active', '(column absent)') AS active,
       o.slug                                      AS org_slug,
       length(s.password_hash)                     AS hash_len,
       (s.password_hash = btrim(s.password_hash))  AS hash_clean,
       '$' || split_part(s.password_hash, '$', 2) ||
       '$' || split_part(s.password_hash, '$', 3)  AS hash_algo,
       (to_regclass('public.sessions') IS NOT NULL
        AND to_regclass('public.auth_attempts') IS NOT NULL) AS auth_tables_present,
       s.id,
       s.org_id
  FROM staff s
  JOIN orgs o ON o.id = s.org_id
 WHERE lower(s.email) = 'chris@fundhub.ai'
 ORDER BY (o.slug = 'fundhub') DESC, o.slug;
