// GENERATED by marketing/broll/scripts/approval-cards.mjs. Do not edit by hand.
// 18 approval cards built with the proof-card template from the real crops in
// marketing/landing-pages/slo/client-wins/deck.json. Amounts are the ones read off each
// crop. Images: public/approval-cards/<id>.png at 3x. Smallest first, climbing to the biggest.

export type ApprovalCard = {
  id: string;
  width: number;
  height: number;
  amount: number;
  lender: string | null;
  category: string;
  source: string;
};

export const APPROVAL_CARDS: ApprovalCard[] = [
  {
    "id": "u-10k-citizens",
    "width": 1680,
    "height": 1912,
    "amount": 10000,
    "lender": "Citizens Bank",
    "category": "credit_card",
    "source": "Drive: Client Approvals/10k approval .png"
  },
  {
    "id": "u-10700-chase-freedom",
    "width": 1680,
    "height": 1912,
    "amount": 10700,
    "lender": "Chase",
    "category": "credit_card",
    "source": "Drive: Screen Shot 2021-12-02 at 5.01.19 PM.png"
  },
  {
    "id": "t-20k-truist",
    "width": 1680,
    "height": 1912,
    "amount": 20000,
    "lender": "Truist",
    "category": "credit_card",
    "source": "Canva Client Wins deck crop s30-a.jpg"
  },
  {
    "id": "g-20k-instant",
    "width": 1680,
    "height": 1912,
    "amount": 20000,
    "lender": null,
    "category": "credit_card",
    "source": "Drive: Inbox — Sort or Delete/Screen Shot 2021-12-03 at 6.33.38 PM.png"
  },
  {
    "id": "d-23k-chase-freedom",
    "width": 1680,
    "height": 1912,
    "amount": 23000,
    "lender": "Chase",
    "category": "credit_card",
    "source": "Drive: Fundhub ads/broll/approvals/23k-chase-freedom-unlimited.jpg"
  },
  {
    "id": "d-24k-navy",
    "width": 1680,
    "height": 1912,
    "amount": 24000,
    "lender": "Navy Federal Credit Union",
    "category": "credit_card",
    "source": "Drive: Fundhub ads/broll/approvals/24k-navy-federal.jpg"
  },
  {
    "id": "d-25k-personal-card",
    "width": 1680,
    "height": 1912,
    "amount": 25000,
    "lender": "Navy Federal Credit Union",
    "category": "credit_card",
    "source": "Drive: Fundhub ads/broll/approvals/25k-personal-card.jpg"
  },
  {
    "id": "t-25k-highland",
    "width": 1680,
    "height": 1912,
    "amount": 25000,
    "lender": "Highland Bank",
    "category": "credit_card",
    "source": "Canva Client Wins deck crop s25-a.jpg"
  },
  {
    "id": "d-30k-navy",
    "width": 1680,
    "height": 1912,
    "amount": 30000,
    "lender": "Navy Federal",
    "category": "credit_card",
    "source": "Drive: Fundhub ads/broll/approvals/30k-navy-federal.jpg"
  },
  {
    "id": "d-41k-chase-ink",
    "width": 1680,
    "height": 1912,
    "amount": 41000,
    "lender": "Chase",
    "category": "credit_card",
    "source": "Drive: Fundhub ads/broll/approvals/41k-chase-ink.jpg"
  },
  {
    "id": "t-50k-keybank",
    "width": 1680,
    "height": 1912,
    "amount": 50000,
    "lender": "KeyBank",
    "category": "credit_card",
    "source": "Canva Client Wins deck crop s37-b.jpg"
  },
  {
    "id": "t-50k-chase",
    "width": 1680,
    "height": 1912,
    "amount": 50000,
    "lender": "Chase",
    "category": "credit_card",
    "source": "Canva Client Wins deck crop s36-a.jpg"
  },
  {
    "id": "d-54k-ink",
    "width": 1680,
    "height": 1912,
    "amount": 54500,
    "lender": "Chase",
    "category": "credit_card",
    "source": "Drive: Fundhub ads/broll/approvals/54k-ink-business.jpg"
  },
  {
    "id": "d-70k-loc",
    "width": 1680,
    "height": 1912,
    "amount": 70000,
    "lender": null,
    "category": "line_of_credit",
    "source": "Drive: Fundhub ads/broll/approvals/70k-line-of-credit-letter.jpg"
  },
  {
    "id": "t-74k-chase-ink",
    "width": 1680,
    "height": 1912,
    "amount": 74000,
    "lender": "Chase",
    "category": "credit_card",
    "source": "Canva Client Wins deck crop s20-a.jpg"
  },
  {
    "id": "d-400k-loc",
    "width": 1680,
    "height": 1912,
    "amount": 400000,
    "lender": null,
    "category": "line_of_credit",
    "source": "Drive: Fundhub ads/broll/approvals/400k-line-of-credit.jpg"
  },
  {
    "id": "d-469k-loc",
    "width": 1680,
    "height": 1912,
    "amount": 469800,
    "lender": null,
    "category": "line_of_credit",
    "source": "Drive: Fundhub ads/broll/approvals/469k-line-of-credit-account.jpg"
  },
  {
    "id": "d-500k-loc",
    "width": 1680,
    "height": 1912,
    "amount": 500000,
    "lender": null,
    "category": "line_of_credit",
    "source": "Drive: Fundhub ads/broll/approvals/500k-line-of-credit-account.jpg"
  }
];
